<?php
/* ═══════════════════════════════════════════════════════════════════════
   THE ABYSS — CONFIG/ZALETY_WADY.PHP
   Punkty Zdolności (PZ): Zaleta kosztuje 1 PZ, Wada oddaje 1 PZ.
   Pula: 10 PZ + 1 co 5 poziomów (+ ewentualny bonus Pochodzenia).
   Zalety + Wady razem: maks. 20. Wolne PZ nie mogą spaść poniżej 0.
   Jedna darmowa zmiana (gracze.zw_zmiana_uzyta), potem tylko MG w Podsumowaniu.
   Zalety działają jako Zdolności („Możliwości”) w teście Zdolności panelu MG.
   Stare definicje zostają w pages/karta.php — tu są kategorie, nowe pozycje,
   Atrybuty testu i pary wykluczeń.
   ═══════════════════════════════════════════════════════════════════════ */

const ZW_PULA_START = 10;
const ZW_CO_POZIOMOW = 5;
const ZW_MAKS = 20;

const ZW_KAT_Z = ['cialo' => 'Ciało', 'zmysly' => 'Zmysły', 'umysl' => 'Umysł', 'nerwy' => 'Nerwy', 'ludzie' => 'Ludzie', 'ulica' => 'Ulica i półświatek', 'miasto' => 'Nowy Jork', 'duch' => 'Wiara i przeczucie', 'natura' => 'Zwierzęta i przyroda'];
const ZW_KAT_W = ['cialo' => 'Ciało', 'choroby' => 'Choroby', 'zmysly' => 'Zmysły', 'umysl' => 'Umysł', 'psych' => 'Psychika i fobie', 'charakter' => 'Charakter', 'nalogi' => 'Nałogi', 'ulica' => 'Ulica i reputacja', 'miasto' => 'Nowy Jork', 'los' => 'Wiara i los', 'natura' => 'Zwierzęta'];

/** nazwa => kategoria (klucz ZW_KAT_Z / ZW_KAT_W) */
const ZW_KATEGORIA_Z = [
    'Żelazne Płuca' => 'cialo',
    'Krzepki' => 'cialo',
    'Szybkie Nogi' => 'cialo',
    'Kocia Zwinność' => 'cialo',
    'Mocny Chwyt' => 'cialo',
    'Atletyczne Ciało' => 'cialo',
    'Szybka Regeneracja' => 'cialo',
    'Zdrowie Jak Żelazo' => 'cialo',
    'Żelazna Wątroba' => 'cialo',
    'Niewrażliwy na Ból' => 'cialo',
    'Drobna Postura' => 'cialo',
    'Sokoli Wzrok' => 'zmysly',
    'Nocny Marek' => 'zmysly',
    'Wyczulony Węch' => 'zmysly',
    'Świetna Pamięć Słuchowa' => 'zmysly',
    'Szósty Zmysł' => 'zmysly',
    'Bystrzak' => 'umysl',
    'Genialny Umysł' => 'umysl',
    'Fotograficzna Pamięć' => 'umysl',
    'Analityczny Umysł' => 'umysl',
    'Poliglota' => 'umysl',
    'Złota Rączka' => 'umysl',
    'Wykształcony' => 'umysl',
    'Zimna Krew' => 'nerwy',
    'Refleks Szachisty' => 'nerwy',
    'Wytrenowane Odruchy' => 'nerwy',
    'Wysoka Tolerancja Stresu' => 'nerwy',
    'Twarda Skóra' => 'nerwy',
    'Pogodny Sen' => 'nerwy',
    'Wrodzony Optymizm' => 'nerwy',
    'Charyzmatyczny' => 'ludzie',
    'Srebrny Język' => 'ludzie',
    'Mistrz Blefu' => 'ludzie',
    'Empatyczny' => 'ludzie',
    'Uliczny Spryt' => 'ulica',
    'Zjawiskowa Uroda' => 'ludzie',
    'Bezkompromisowy' => 'ludzie',
    'Znajomości w Półświatku' => 'ulica',
    'Bogate Dziedzictwo' => 'ludzie',
    'Oburęczny' => 'cialo',
    'Lekka Ręka' => 'ulica',
    'Widzenie w mroku' => 'zmysly',
    'Słuch absolutny' => 'zmysly',
    'Wyczucie kłamstwa' => 'zmysly',
    'Czytanie z ruchu warg' => 'zmysly',
    'Wyczucie zasadzki' => 'zmysly',
    'Oko rzeczoznawcy' => 'zmysly',
    'Wykrywanie podsłuchu' => 'zmysly',
    'Pamięć zapachów' => 'zmysly',
    'Odporność na trucizny' => 'cialo',
    'Czuwanie' => 'cialo',
    'Kontorsjonista' => 'cialo',
    'Parkour' => 'cialo',
    'Hartowanie' => 'cialo',
    'Rachmistrz' => 'umysl',
    'Intuicja językowa' => 'umysl',
    'Łamacz szyfrów' => 'umysl',
    'Pamięć twarzy' => 'umysl',
    'Zmysł kierunku' => 'umysl',
    'Szybkie czytanie' => 'umysl',
    'Dedukcja z drobiazgów' => 'umysl',
    'Umysł-forteca' => 'umysl',
    'Dotyk mechanika' => 'umysl',
    'Zmysł do elektroniki' => 'umysl',
    'Kameleon' => 'ludzie',
    'Hipnotyczny głos' => 'ludzie',
    'Naśladowanie głosów' => 'ludzie',
    'Mistrz przebrań' => 'ludzie',
    'Autorytet' => 'ludzie',
    'Zaufana twarz' => 'ludzie',
    'Czytanie tłumu' => 'ludzie',
    'Etykieta elit' => 'ludzie',
    'Zmysł do glin' => 'ulica',
    'Mowa ulicy' => 'ulica',
    'Znaki syndykatu' => 'ulica',
    'Paser' => 'ulica',
    'Ucieczka przed pościgiem' => 'ulica',
    'Nerwy złodzieja' => 'ulica',
    'Przetrwanie w slumsach' => 'ulica',
    'Podziemny Nowy Jork' => 'miasto',
    'Dachy Manhattanu' => 'miasto',
    'Taksówkarz' => 'miasto',
    'Nabrzeże' => 'miasto',
    'Plotki salonów' => 'miasto',
    'Dzielnica rodzinna' => 'miasto',
    'Niezłomna wola' => 'duch',
    'Obrzędy Katedry' => 'duch',
    'Spowiednik' => 'duch',
    'Spokój ducha' => 'duch',
    'Łut szczęścia' => 'duch',
    'Język zwierząt' => 'natura',
    'Tresura' => 'natura',
    'Jeździec urodzony' => 'natura',
    'Zielarz miejski' => 'natura',
    'Tropiciel' => 'natura',
];
const ZW_KATEGORIA_W = [
    'Brak Kończyny' => 'cialo',
    'Całkowita Ślepota' => 'cialo',
    'Głuchy' => 'cialo',
    'Jednooki' => 'cialo',
    'Oszpecony' => 'cialo',
    'Utykający' => 'cialo',
    'Hemofiliak' => 'cialo',
    'Astma' => 'choroby',
    'Choroba Serca' => 'choroby',
    'Cukrzyca' => 'choroby',
    'Epilepsja' => 'choroby',
    'Migreny' => 'choroby',
    'Alergie' => 'choroby',
    'Niska Odporność' => 'choroby',
    'Bezsenność' => 'choroby',
    'Reumatyzm' => 'choroby',
    'Wolne Gojenie' => 'choroby',
    'Krótkowidz' => 'zmysly',
    'Daltonizm' => 'zmysly',
    'Niedosłuch' => 'zmysly',
    'Słabeusz' => 'cialo',
    'Jąkanie' => 'umysl',
    'Depresja' => 'psych',
    'Lęki Napadowe' => 'psych',
    'Trauma Pourazowa' => 'psych',
    'Natręctwa' => 'psych',
    'Rozproszenie Uwagi' => 'psych',
    'Paranoik' => 'psych',
    'Furiat' => 'charakter',
    'Tchórz' => 'charakter',
    'Naiwny' => 'charakter',
    'Odludek' => 'charakter',
    'Gadatliwy' => 'charakter',
    'Leniwy' => 'charakter',
    'Impulsywność' => 'charakter',
    'Pycha' => 'charakter',
    'Skąpiec' => 'charakter',
    'Mizantrop' => 'charakter',
    'Brak Empatii' => 'charakter',
    'Klaustrofobia' => 'psych',
    'Lęk Wysokości' => 'psych',
    'Lęk Tłumu' => 'psych',
    'Nałogowiec' => 'nalogi',
    'Hazardzista' => 'nalogi',
    'Kleptomania' => 'nalogi',
    'Zła Reputacja' => 'ulica',
    'Pechowiec' => 'los',
    'Ociężały Umysł' => 'umysl',
    'Dysleksja' => 'umysl',
    'Hipochondryk' => 'psych',
    'Nocna ślepota' => 'zmysly',
    'Brak węchu' => 'zmysly',
    'Nadwrażliwość na hałas' => 'zmysly',
    'Kruche kości' => 'cialo',
    'Choroba lokomocyjna' => 'cialo',
    'Niezdarny' => 'cialo',
    'Słaba głowa' => 'cialo',
    'Roztargniony' => 'umysl',
    'Brak orientacji' => 'umysl',
    'Analfabeta techniczny' => 'umysl',
    'Nieufny' => 'charakter',
    'Szczerość do bólu' => 'charakter',
    'Wstydliwy' => 'charakter',
    'Obcy akcent' => 'ulica',
    'Dłużnik syndykatu' => 'ulica',
    'Kartoteka policyjna' => 'ulica',
    'Wróg w półświatku' => 'ulica',
    'Poszukiwany' => 'ulica',
    'Znana twarz' => 'ulica',
    'Przybysz' => 'miasto',
    'Wykluczony z dzielnicy' => 'miasto',
    'Lęk przed ciemnością' => 'psych',
    'Lęk przed wodą' => 'psych',
    'Koszmary' => 'psych',
    'Przesądny' => 'los',
    'Fanatyk' => 'los',
    'Kryzys wiary' => 'los',
    'Zwierzęta jej nie lubią' => 'natura',
    'Lęk przed psami' => 'natura',
];

/** Atrybut(y) testu Zdolności dla Zalety (S, Z, W, I, Zm, Ch; „+” = średnia). */
const ZW_TEST = [
    'Żelazne Płuca' => 'W',
    'Krzepki' => 'S',
    'Szybkie Nogi' => 'Z',
    'Kocia Zwinność' => 'Z',
    'Mocny Chwyt' => 'S',
    'Atletyczne Ciało' => 'S+Z',
    'Szybka Regeneracja' => 'W',
    'Zdrowie Jak Żelazo' => 'W',
    'Żelazna Wątroba' => 'W',
    'Niewrażliwy na Ból' => 'W',
    'Drobna Postura' => 'Z',
    'Sokoli Wzrok' => 'Zm',
    'Nocny Marek' => 'W',
    'Wyczulony Węch' => 'Zm',
    'Świetna Pamięć Słuchowa' => 'Zm+I',
    'Szósty Zmysł' => 'Zm',
    'Bystrzak' => 'I',
    'Genialny Umysł' => 'I',
    'Fotograficzna Pamięć' => 'I',
    'Analityczny Umysł' => 'I',
    'Poliglota' => 'I',
    'Złota Rączka' => 'I+Z',
    'Wykształcony' => 'I',
    'Zimna Krew' => 'W+Ch',
    'Refleks Szachisty' => 'I+Z',
    'Wytrenowane Odruchy' => 'Z',
    'Wysoka Tolerancja Stresu' => 'W',
    'Twarda Skóra' => 'W',
    'Pogodny Sen' => 'W',
    'Wrodzony Optymizm' => 'Ch',
    'Charyzmatyczny' => 'Ch',
    'Srebrny Język' => 'Ch',
    'Mistrz Blefu' => 'Ch',
    'Empatyczny' => 'Ch+Zm',
    'Uliczny Spryt' => 'I+Zm',
    'Zjawiskowa Uroda' => 'Ch',
    'Bezkompromisowy' => 'Ch+W',
    'Znajomości w Półświatku' => 'Ch+I',
    'Bogate Dziedzictwo' => 'Ch',
    'Oburęczny' => 'Z',
    'Lekka Ręka' => 'Z',
    'Widzenie w mroku' => 'Zm',
    'Słuch absolutny' => 'Zm',
    'Wyczucie kłamstwa' => 'Zm+Ch',
    'Czytanie z ruchu warg' => 'Zm+I',
    'Wyczucie zasadzki' => 'Zm+Z',
    'Oko rzeczoznawcy' => 'Zm+I',
    'Wykrywanie podsłuchu' => 'Zm+I',
    'Pamięć zapachów' => 'Zm',
    'Odporność na trucizny' => 'W',
    'Czuwanie' => 'W',
    'Kontorsjonista' => 'Z',
    'Parkour' => 'Z+S',
    'Hartowanie' => 'W',
    'Rachmistrz' => 'I',
    'Intuicja językowa' => 'I',
    'Łamacz szyfrów' => 'I',
    'Pamięć twarzy' => 'I+Zm',
    'Zmysł kierunku' => 'I+Zm',
    'Szybkie czytanie' => 'I',
    'Dedukcja z drobiazgów' => 'I+Zm',
    'Umysł-forteca' => 'I+W',
    'Dotyk mechanika' => 'I+Z',
    'Zmysł do elektroniki' => 'I',
    'Kameleon' => 'Ch+Zm',
    'Hipnotyczny głos' => 'Ch',
    'Naśladowanie głosów' => 'Ch+Zm',
    'Mistrz przebrań' => 'Ch+Z',
    'Autorytet' => 'Ch',
    'Zaufana twarz' => 'Ch',
    'Czytanie tłumu' => 'Ch+Zm',
    'Etykieta elit' => 'Ch+I',
    'Zmysł do glin' => 'Zm+Ch',
    'Mowa ulicy' => 'Ch',
    'Znaki syndykatu' => 'I+Ch',
    'Paser' => 'I+Ch',
    'Ucieczka przed pościgiem' => 'Z+Zm',
    'Nerwy złodzieja' => 'Z+W',
    'Przetrwanie w slumsach' => 'W+I',
    'Podziemny Nowy Jork' => 'I',
    'Dachy Manhattanu' => 'Z+I',
    'Taksówkarz' => 'I',
    'Nabrzeże' => 'I+Ch',
    'Plotki salonów' => 'Ch+I',
    'Dzielnica rodzinna' => 'Ch',
    'Niezłomna wola' => 'W+Ch',
    'Obrzędy Katedry' => 'I+Ch',
    'Spowiednik' => 'Ch',
    'Spokój ducha' => 'W',
    'Łut szczęścia' => 'Zm+Ch',
    'Język zwierząt' => 'Ch',
    'Tresura' => 'Ch+I',
    'Jeździec urodzony' => 'Z',
    'Zielarz miejski' => 'I+Zm',
    'Tropiciel' => 'Zm+I',
];

/** Nowe pozycje (dopisywane do katalogów z karta.php). */
const ZW_NOWE_ZALETY = [
    'Widzenie w mroku' => ['grupa' => 'Zmysły', 'opis' => 'Rozróżnia kształty i ruch w niemal całkowitej ciemności, np. w tunelach metra bez latarki.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Rozróżnia kształty i ruch w niemal całkowitej ciemności, np. w tunelach metra bez latarki.'],
    'Słuch absolutny' => ['grupa' => 'Zmysły', 'opis' => 'Rozpoznaje głos przez ścianę, liczy kroki na schodach, słyszy odbezpieczenie broni w tłumie.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Rozpoznaje głos przez ścianę, liczy kroki na schodach, słyszy odbezpieczenie broni w tłumie.'],
    'Wyczucie kłamstwa' => ['grupa' => 'Zmysły', 'opis' => 'Test, czy rozmówca kłamie — z mikroekspresji, oddechu i tonu głosu.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Test, czy rozmówca kłamie — z mikroekspresji, oddechu i tonu głosu.'],
    'Czytanie z ruchu warg' => ['grupa' => 'Zmysły', 'opis' => 'Rozumie rozmowę z drugiego końca sali albo z nagrania bez dźwięku.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Rozumie rozmowę z drugiego końca sali albo z nagrania bez dźwięku.'],
    'Wyczucie zasadzki' => ['grupa' => 'Zmysły', 'opis' => 'Tuż przed atakiem zauważa, że coś jest nie tak — może nie dać się zaskoczyć.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Tuż przed atakiem zauważa, że coś jest nie tak — może nie dać się zaskoczyć.'],
    'Oko rzeczoznawcy' => ['grupa' => 'Zmysły', 'opis' => 'Odróżnia oryginał od podróbki: obraz, zegarek, banknot, dokument.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Odróżnia oryginał od podróbki: obraz, zegarek, banknot, dokument.'],
    'Wykrywanie podsłuchu' => ['grupa' => 'Zmysły', 'opis' => 'Zauważa pluskwy, ukryte kamery i ślady po montażu w pokoju.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Zauważa pluskwy, ukryte kamery i ślady po montażu w pokoju.'],
    'Pamięć zapachów' => ['grupa' => 'Zmysły', 'opis' => 'Rozpoznaje osobę, miejsce albo substancję po zapachu sprzed tygodni.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Rozpoznaje osobę, miejsce albo substancję po zapachu sprzed tygodni.'],
    'Odporność na trucizny' => ['grupa' => 'Ciało', 'opis' => 'Test, czy trucizna lub narkotyk w ogóle zadziała.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Test, czy trucizna lub narkotyk w ogóle zadziała.'],
    'Czuwanie' => ['grupa' => 'Ciało', 'opis' => 'Funkcjonuje 48 godzin bez snu bez kar do testów.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Funkcjonuje 48 godzin bez snu bez kar do testów.'],
    'Kontorsjonista' => ['grupa' => 'Ciało', 'opis' => 'Przeciska się przez kraty, szyby wentylacyjne i wyswobadza z więzów.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Przeciska się przez kraty, szyby wentylacyjne i wyswobadza z więzów.'],
    'Parkour' => ['grupa' => 'Ciało', 'opis' => 'Skoki między dachami i przejścia, których bez tego nikt by nie próbował.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Skoki między dachami i przejścia, których bez tego nikt by nie próbował.'],
    'Hartowanie' => ['grupa' => 'Ciało', 'opis' => 'Znosi mróz nad Hudsonem i upał w maszynowni bez utraty sił.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Znosi mróz nad Hudsonem i upał w maszynowni bez utraty sił.'],
    'Rachmistrz' => ['grupa' => 'Umysł', 'opis' => 'Liczy w pamięci szanse, kursy, trajektorie i ukryte błędy w księgach.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Liczy w pamięci szanse, kursy, trajektorie i ukryte błędy w księgach.'],
    'Intuicja językowa' => ['grupa' => 'Umysł', 'opis' => 'Łapie ogólny sens rozmowy w języku, którego nie zna.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Łapie ogólny sens rozmowy w języku, którego nie zna.'],
    'Łamacz szyfrów' => ['grupa' => 'Umysł', 'opis' => 'Próbuje rozszyfrować kod bez klucza i sprzętu.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Próbuje rozszyfrować kod bez klucza i sprzętu.'],
    'Pamięć twarzy' => ['grupa' => 'Umysł', 'opis' => 'Rozpoznaje osobę po latach, w przebraniu albo na ziarnistym zdjęciu.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Rozpoznaje osobę po latach, w przebraniu albo na ziarnistym zdjęciu.'],
    'Zmysł kierunku' => ['grupa' => 'Umysł', 'opis' => 'Nie gubi się w tunelach, kanałach i obcych dzielnicach bez mapy.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Nie gubi się w tunelach, kanałach i obcych dzielnicach bez mapy.'],
    'Szybkie czytanie' => ['grupa' => 'Umysł', 'opis' => 'Przegląda teczkę albo księgę w minutę i wie, co jest istotne.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Przegląda teczkę albo księgę w minutę i wie, co jest istotne.'],
    'Dedukcja z drobiazgów' => ['grupa' => 'Umysł', 'opis' => 'Z plamy, zapachu i butów wnioskuje, skąd ktoś przyszedł i co robił.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Z plamy, zapachu i butów wnioskuje, skąd ktoś przyszedł i co robił.'],
    'Umysł-forteca' => ['grupa' => 'Umysł', 'opis' => 'Test, czy przesłuchanie albo narkotyk prawdy wydobędą informacje.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Test, czy przesłuchanie albo narkotyk prawdy wydobędą informacje.'],
    'Dotyk mechanika' => ['grupa' => 'Umysł', 'opis' => 'Po odgłosie silnika i dotyku wie, co się zepsuło i jak to prowizorycznie naprawić.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Po odgłosie silnika i dotyku wie, co się zepsuło i jak to prowizorycznie naprawić.'],
    'Zmysł do elektroniki' => ['grupa' => 'Umysł', 'opis' => 'Wyczuwa, gdzie są kable, czujniki i słaby punkt zabezpieczeń budynku.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Wyczuwa, gdzie są kable, czujniki i słaby punkt zabezpieczeń budynku.'],
    'Kameleon' => ['grupa' => 'Ludzie', 'opis' => 'Wtapia się w każde towarzystwo: bal na 5th Ave, melina w Bronksie, zebranie związku.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Wtapia się w każde towarzystwo: bal na 5th Ave, melina w Bronksie, zebranie związku.'],
    'Hipnotyczny głos' => ['grupa' => 'Ludzie', 'opis' => 'Uspokaja tłum, panikarza albo zwierzę samym tonem.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Uspokaja tłum, panikarza albo zwierzę samym tonem.'],
    'Naśladowanie głosów' => ['grupa' => 'Ludzie', 'opis' => 'Mówi jak ktoś inny: przez telefon, domofon, za drzwiami.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Mówi jak ktoś inny: przez telefon, domofon, za drzwiami.'],
    'Mistrz przebrań' => ['grupa' => 'Ludzie', 'opis' => 'Charakteryzacja tak dobra, że znajomi nie rozpoznają postaci.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Charakteryzacja tak dobra, że znajomi nie rozpoznają postaci.'],
    'Autorytet' => ['grupa' => 'Ludzie', 'opis' => 'W kryzysie obcy wykonują polecenia postaci bez pytania.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. W kryzysie obcy wykonują polecenia postaci bez pytania.'],
    'Zaufana twarz' => ['grupa' => 'Ludzie', 'opis' => 'Nieznajomi zwierzają się jej i powierzają sekrety.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Nieznajomi zwierzają się jej i powierzają sekrety.'],
    'Czytanie tłumu' => ['grupa' => 'Ludzie', 'opis' => 'Wyczuwa nastrój sali i moment, w którym zamieni się w zamieszki.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Wyczuwa nastrój sali i moment, w którym zamieni się w zamieszki.'],
    'Etykieta elit' => ['grupa' => 'Ludzie', 'opis' => 'Porusza się wśród arystokracji bez faux pas.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Porusza się wśród arystokracji bez faux pas.'],
    'Zmysł do glin' => ['grupa' => 'Ulica i półświatek', 'opis' => 'Rozpoznaje tajniaka, informatora i podstawioną furgonetkę.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Rozpoznaje tajniaka, informatora i podstawioną furgonetkę.'],
    'Mowa ulicy' => ['grupa' => 'Ulica i półświatek', 'opis' => 'Zna slang, znaki gangów i graffiti — rozumie, czyj to teren.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Zna slang, znaki gangów i graffiti — rozumie, czyj to teren.'],
    'Znaki syndykatu' => ['grupa' => 'Ulica i półświatek', 'opis' => 'Odczytuje i wysyła ukryte sygnały rodzin mafijnych.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Odczytuje i wysyła ukryte sygnały rodzin mafijnych.'],
    'Paser' => ['grupa' => 'Ulica i półświatek', 'opis' => 'Wie, komu i za ile sprzedać gorący towar.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Wie, komu i za ile sprzedać gorący towar.'],
    'Ucieczka przed pościgiem' => ['grupa' => 'Ulica i półświatek', 'opis' => 'Znika w tłumie, przez bramy i podwórka — test, czy zgubi ogon.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Znika w tłumie, przez bramy i podwórka — test, czy zgubi ogon.'],
    'Nerwy złodzieja' => ['grupa' => 'Ulica i półświatek', 'opis' => 'Działa spokojnie z alarmem za plecami: ręce nie drżą przy sejfie.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Działa spokojnie z alarmem za plecami: ręce nie drżą przy sejfie.'],
    'Przetrwanie w slumsach' => ['grupa' => 'Ulica i półświatek', 'opis' => 'Znajduje nocleg, jedzenie i leki bez grosza przy duszy.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Znajduje nocleg, jedzenie i leki bez grosza przy duszy.'],
    'Podziemny Nowy Jork' => ['grupa' => 'Nowy Jork', 'opis' => 'Zna tunele metra, kanały i zapomniane stacje.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Zna tunele metra, kanały i zapomniane stacje.'],
    'Dachy Manhattanu' => ['grupa' => 'Nowy Jork', 'opis' => 'Przemieszcza się po dachach jak po ulicach.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Przemieszcza się po dachach jak po ulicach.'],
    'Taksówkarz' => ['grupa' => 'Nowy Jork', 'opis' => 'Zna każdy skrót, korek i objazd o każdej porze.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Zna każdy skrót, korek i objazd o każdej porze.'],
    'Nabrzeże' => ['grupa' => 'Nowy Jork', 'opis' => 'Zna doki, marynarzy i rozkład statków.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Zna doki, marynarzy i rozkład statków.'],
    'Plotki salonów' => ['grupa' => 'Nowy Jork', 'opis' => 'Wie, kto z kim, kto zbankrutował i kto wydaje przyjęcie w sobotę.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Wie, kto z kim, kto zbankrutował i kto wydaje przyjęcie w sobotę.'],
    'Dzielnica rodzinna' => ['grupa' => 'Nowy Jork', 'opis' => 'We własnej dzielnicy każdy ją zna — sąsiedzi mogą ją ukryć.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. We własnej dzielnicy każdy ją zna — sąsiedzi mogą ją ukryć.'],
    'Niezłomna wola' => ['grupa' => 'Wiara i przeczucie', 'opis' => 'Test, czy zastraszenie, szantaż albo groźba w ogóle działają.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Test, czy zastraszenie, szantaż albo groźba w ogóle działają.'],
    'Obrzędy Katedry' => ['grupa' => 'Wiara i przeczucie', 'opis' => 'Zna liturgię, śluby i egzorcyzmy — może je poprowadzić lub rozpoznać fałszerza.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Zna liturgię, śluby i egzorcyzmy — może je poprowadzić lub rozpoznać fałszerza.'],
    'Spowiednik' => ['grupa' => 'Wiara i przeczucie', 'opis' => 'Ludzie wyznają jej grzechy, których nie powiedzieli nikomu.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Ludzie wyznają jej grzechy, których nie powiedzieli nikomu.'],
    'Spokój ducha' => ['grupa' => 'Wiara i przeczucie', 'opis' => 'Po traumie test, czy uniknie Wady psychicznej w Podsumowaniu.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Po traumie test, czy uniknie Wady psychicznej w Podsumowaniu.'],
    'Łut szczęścia' => ['grupa' => 'Wiara i przeczucie', 'opis' => 'Test szczęścia tam, gdzie inni zdają się na czysty los.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Test szczęścia tam, gdzie inni zdają się na czysty los.'],
    'Język zwierząt' => ['grupa' => 'Zwierzęta i przyroda', 'opis' => 'Uspokaja psa stróżującego, konia w panice, ptaki na dachu.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Uspokaja psa stróżującego, konia w panice, ptaki na dachu.'],
    'Tresura' => ['grupa' => 'Zwierzęta i przyroda', 'opis' => 'Uczy zwierzę prostych komend w kilka dni.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Uczy zwierzę prostych komend w kilka dni.'],
    'Jeździec urodzony' => ['grupa' => 'Zwierzęta i przyroda', 'opis' => 'Utrzymuje się na koniu w galopie, skoku i spłoszeniu.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Utrzymuje się na koniu w galopie, skoku i spłoszeniu.'],
    'Zielarz miejski' => ['grupa' => 'Zwierzęta i przyroda', 'opis' => 'Rozpoznaje rośliny z Central Parku i nieużytków, trujące i lecznicze.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Rozpoznaje rośliny z Central Parku i nieużytków, trujące i lecznicze.'],
    'Tropiciel' => ['grupa' => 'Zwierzęta i przyroda', 'opis' => 'Idzie po śladach w parku, na śniegu i w błocie budowy.', 'wplyw' => 'Zdolność: umożliwia test, którego bez niej nie da się wykonać. Idzie po śladach w parku, na śniegu i w błocie budowy.'],
];
const ZW_NOWE_WADY = [
    'Nocna ślepota' => ['grupa' => 'Zmysły', 'opis' => 'Po zmroku widzi tylko kontury — kary do testów obserwacji w ciemności.', 'wplyw' => 'Po zmroku widzi tylko kontury — kary do testów obserwacji w ciemności.'],
    'Brak węchu' => ['grupa' => 'Zmysły', 'opis' => 'Nie poczuje gazu, dymu ani trucizny w jedzeniu.', 'wplyw' => 'Nie poczuje gazu, dymu ani trucizny w jedzeniu.'],
    'Nadwrażliwość na hałas' => ['grupa' => 'Zmysły', 'opis' => 'Głośna muzyka, strzały i syreny wytrącają ją z równowagi.', 'wplyw' => 'Głośna muzyka, strzały i syreny wytrącają ją z równowagi.'],
    'Kruche kości' => ['grupa' => 'Ciało', 'opis' => 'Upadki i ciosy łatwiej kończą się Urazem.', 'wplyw' => 'Upadki i ciosy łatwiej kończą się Urazem.'],
    'Choroba lokomocyjna' => ['grupa' => 'Ciało', 'opis' => 'Pościg autem, łódź po zatoce czy kolejka górska — mdłości i kary.', 'wplyw' => 'Pościg autem, łódź po zatoce czy kolejka górska — mdłości i kary.'],
    'Niezdarny' => ['grupa' => 'Ciało', 'opis' => 'Potyka się, strąca rzeczy, nadepnie komuś na stopę na balu.', 'wplyw' => 'Potyka się, strąca rzeczy, nadepnie komuś na stopę na balu.'],
    'Słaba głowa' => ['grupa' => 'Ciało', 'opis' => 'Po dwóch drinkach traci kontrolę nad językiem i nogami.', 'wplyw' => 'Po dwóch drinkach traci kontrolę nad językiem i nogami.'],
    'Roztargniony' => ['grupa' => 'Umysł', 'opis' => 'Zapomina o spotkaniach, zostawia klucze, gubi wątek.', 'wplyw' => 'Zapomina o spotkaniach, zostawia klucze, gubi wątek.'],
    'Brak orientacji' => ['grupa' => 'Umysł', 'opis' => 'Gubi się w obcej dzielnicy i w metrze nawet z mapą.', 'wplyw' => 'Gubi się w obcej dzielnicy i w metrze nawet z mapą.'],
    'Analfabeta techniczny' => ['grupa' => 'Umysł', 'opis' => 'Nie radzi sobie z maszynami, zamkami elektronicznymi i komputerami.', 'wplyw' => 'Nie radzi sobie z maszynami, zamkami elektronicznymi i komputerami.'],
    'Nieufny' => ['grupa' => 'Charakter', 'opis' => 'Nie przyjmie pomocy ani informacji od obcych bez dowodu.', 'wplyw' => 'Nie przyjmie pomocy ani informacji od obcych bez dowodu.'],
    'Szczerość do bólu' => ['grupa' => 'Charakter', 'opis' => 'Nie umie kłamać — blef i ukrywanie prawdy prawie zawsze się nie udają.', 'wplyw' => 'Nie umie kłamać — blef i ukrywanie prawdy prawie zawsze się nie udają.'],
    'Wstydliwy' => ['grupa' => 'Charakter', 'opis' => 'Unika uwagi — występy publiczne, flirt i przemowy idą jej opornie.', 'wplyw' => 'Unika uwagi — występy publiczne, flirt i przemowy idą jej opornie.'],
    'Obcy akcent' => ['grupa' => 'Ulica i reputacja', 'opis' => 'Od razu wiadomo, że nie jest stąd — trudniej wtopić się w tłum.', 'wplyw' => 'Od razu wiadomo, że nie jest stąd — trudniej wtopić się w tłum.'],
    'Dłużnik syndykatu' => ['grupa' => 'Ulica i reputacja', 'opis' => 'Jest winna pieniądze rodzinie — windykatorzy mogą pojawić się w każdej Opowieści.', 'wplyw' => 'Jest winna pieniądze rodzinie — windykatorzy mogą pojawić się w każdej Opowieści.'],
    'Kartoteka policyjna' => ['grupa' => 'Ulica i reputacja', 'opis' => 'Ma akta w NYPD: kontrole, podejrzenia i trudność z legalną pracą.', 'wplyw' => 'Ma akta w NYPD: kontrole, podejrzenia i trudność z legalną pracą.'],
    'Wróg w półświatku' => ['grupa' => 'Ulica i reputacja', 'opis' => 'Ktoś wpływowy chce jej krzywdy i ma ludzi na mieście.', 'wplyw' => 'Ktoś wpływowy chce jej krzywdy i ma ludzi na mieście.'],
    'Poszukiwany' => ['grupa' => 'Ulica i reputacja', 'opis' => 'Wisi list gończy — zdjęcie na posterunkach i w gazetach.', 'wplyw' => 'Wisi list gończy — zdjęcie na posterunkach i w gazetach.'],
    'Znana twarz' => ['grupa' => 'Ulica i reputacja', 'opis' => 'Łatwo ją rozpoznać — przebranie i anonimowość prawie nie działają.', 'wplyw' => 'Łatwo ją rozpoznać — przebranie i anonimowość prawie nie działają.'],
    'Przybysz' => ['grupa' => 'Nowy Jork', 'opis' => 'Świeżo w mieście: nie zna dzielnic, cen, ludzi ani zasad.', 'wplyw' => 'Świeżo w mieście: nie zna dzielnic, cen, ludzi ani zasad.'],
    'Wykluczony z dzielnicy' => ['grupa' => 'Nowy Jork', 'opis' => 'We własnej dzielnicy ma złą sławę — sąsiedzi donoszą, zamiast pomagać.', 'wplyw' => 'We własnej dzielnicy ma złą sławę — sąsiedzi donoszą, zamiast pomagać.'],
    'Lęk przed ciemnością' => ['grupa' => 'Psychika i fobie', 'opis' => 'W ciemnych tunelach i piwnicach panikuje.', 'wplyw' => 'W ciemnych tunelach i piwnicach panikuje.'],
    'Lęk przed wodą' => ['grupa' => 'Psychika i fobie', 'opis' => 'Nie wejdzie na łódź ani do wody bez paniki.', 'wplyw' => 'Nie wejdzie na łódź ani do wody bez paniki.'],
    'Koszmary' => ['grupa' => 'Psychika i fobie', 'opis' => 'Źle śpi — rano bywa rozkojarzona i zmęczona.', 'wplyw' => 'Źle śpi — rano bywa rozkojarzona i zmęczona.'],
    'Przesądny' => ['grupa' => 'Wiara i los', 'opis' => 'Czarny kot, drabina, zła wróżba — potrafi porzucić plan z powodu znaku.', 'wplyw' => 'Czarny kot, drabina, zła wróżba — potrafi porzucić plan z powodu znaku.'],
    'Fanatyk' => ['grupa' => 'Wiara i los', 'opis' => 'Wiara albo idea ponad wszystko — łatwo ją sprowokować i zmanipulować.', 'wplyw' => 'Wiara albo idea ponad wszystko — łatwo ją sprowokować i zmanipulować.'],
    'Kryzys wiary' => ['grupa' => 'Wiara i los', 'opis' => 'Straciła sens i oparcie — wątpi we wszystko, łatwo się poddaje.', 'wplyw' => 'Straciła sens i oparcie — wątpi we wszystko, łatwo się poddaje.'],
    'Zwierzęta jej nie lubią' => ['grupa' => 'Zwierzęta', 'opis' => 'Psy warczą, konie się płoszą, koty uciekają.', 'wplyw' => 'Psy warczą, konie się płoszą, koty uciekają.'],
    'Lęk przed psami' => ['grupa' => 'Zwierzęta', 'opis' => 'Na widok psa zamiera albo ucieka.', 'wplyw' => 'Na widok psa zamiera albo ucieka.'],
];

/** Pary wykluczeń — działają w obie strony. */
const ZW_PARY = [
    ['Całkowita Ślepota', 'Sokoli Wzrok'],
    ['Całkowita Ślepota', 'Widzenie w mroku'],
    ['Całkowita Ślepota', 'Czytanie z ruchu warg'],
    ['Całkowita Ślepota', 'Oko rzeczoznawcy'],
    ['Całkowita Ślepota', 'Pamięć twarzy'],
    ['Całkowita Ślepota', 'Mistrz przebrań'],
    ['Całkowita Ślepota', 'Szybkie czytanie'],
    ['Całkowita Ślepota', 'Fotograficzna Pamięć'],
    ['Całkowita Ślepota', 'Tropiciel'],
    ['Całkowita Ślepota', 'Wykrywanie podsłuchu'],
    ['Całkowita Ślepota', 'Jednooki'],
    ['Całkowita Ślepota', 'Krótkowidz'],
    ['Całkowita Ślepota', 'Daltonizm'],
    ['Całkowita Ślepota', 'Nocna ślepota'],
    ['Całkowita Ślepota', 'Nocny Marek'],
    ['Jednooki', 'Sokoli Wzrok'],
    ['Krótkowidz', 'Sokoli Wzrok'],
    ['Krótkowidz', 'Oko rzeczoznawcy'],
    ['Nocna ślepota', 'Widzenie w mroku'],
    ['Nocna ślepota', 'Nocny Marek'],
    ['Daltonizm', 'Oko rzeczoznawcy'],
    ['Głuchy', 'Świetna Pamięć Słuchowa'],
    ['Głuchy', 'Słuch absolutny'],
    ['Głuchy', 'Naśladowanie głosów'],
    ['Głuchy', 'Intuicja językowa'],
    ['Głuchy', 'Niedosłuch'],
    ['Głuchy', 'Nadwrażliwość na hałas'],
    ['Niedosłuch', 'Słuch absolutny'],
    ['Niedosłuch', 'Świetna Pamięć Słuchowa'],
    ['Brak węchu', 'Wyczulony Węch'],
    ['Brak węchu', 'Pamięć zapachów'],
    ['Brak Kończyny', 'Oburęczny'],
    ['Brak Kończyny', 'Parkour'],
    ['Brak Kończyny', 'Szybkie Nogi'],
    ['Brak Kończyny', 'Kontorsjonista'],
    ['Brak Kończyny', 'Atletyczne Ciało'],
    ['Utykający', 'Szybkie Nogi'],
    ['Utykający', 'Parkour'],
    ['Utykający', 'Kocia Zwinność'],
    ['Utykający', 'Atletyczne Ciało'],
    ['Utykający', 'Dachy Manhattanu'],
    ['Utykający', 'Ucieczka przed pościgiem'],
    ['Słabeusz', 'Krzepki'],
    ['Słabeusz', 'Mocny Chwyt'],
    ['Słabeusz', 'Atletyczne Ciało'],
    ['Drobna Postura', 'Krzepki'],
    ['Kruche kości', 'Zdrowie Jak Żelazo'],
    ['Hemofiliak', 'Zdrowie Jak Żelazo'],
    ['Wolne Gojenie', 'Szybka Regeneracja'],
    ['Niska Odporność', 'Zdrowie Jak Żelazo'],
    ['Astma', 'Żelazne Płuca'],
    ['Choroba Serca', 'Atletyczne Ciało'],
    ['Choroba Serca', 'Zdrowie Jak Żelazo'],
    ['Cukrzyca', 'Zdrowie Jak Żelazo'],
    ['Epilepsja', 'Zdrowie Jak Żelazo'],
    ['Reumatyzm', 'Kocia Zwinność'],
    ['Reumatyzm', 'Kontorsjonista'],
    ['Bezsenność', 'Pogodny Sen'],
    ['Bezsenność', 'Czuwanie'],
    ['Koszmary', 'Pogodny Sen'],
    ['Słaba głowa', 'Żelazna Wątroba'],
    ['Niezdarny', 'Kocia Zwinność'],
    ['Niezdarny', 'Lekka Ręka'],
    ['Niezdarny', 'Kontorsjonista'],
    ['Niezdarny', 'Parkour'],
    ['Niezdarny', 'Wytrenowane Odruchy'],
    ['Ociężały Umysł', 'Bystrzak'],
    ['Ociężały Umysł', 'Genialny Umysł'],
    ['Ociężały Umysł', 'Analityczny Umysł'],
    ['Ociężały Umysł', 'Rachmistrz'],
    ['Ociężały Umysł', 'Fotograficzna Pamięć'],
    ['Ociężały Umysł', 'Łamacz szyfrów'],
    ['Ociężały Umysł', 'Szybkie czytanie'],
    ['Ociężały Umysł', 'Dedukcja z drobiazgów'],
    ['Dysleksja', 'Szybkie czytanie'],
    ['Roztargniony', 'Fotograficzna Pamięć'],
    ['Brak orientacji', 'Zmysł kierunku'],
    ['Brak orientacji', 'Taksówkarz'],
    ['Brak orientacji', 'Podziemny Nowy Jork'],
    ['Analfabeta techniczny', 'Złota Rączka'],
    ['Analfabeta techniczny', 'Dotyk mechanika'],
    ['Analfabeta techniczny', 'Zmysł do elektroniki'],
    ['Jąkanie', 'Srebrny Język'],
    ['Jąkanie', 'Hipnotyczny głos'],
    ['Jąkanie', 'Naśladowanie głosów'],
    ['Tchórz', 'Zimna Krew'],
    ['Tchórz', 'Niezłomna wola'],
    ['Tchórz', 'Bezkompromisowy'],
    ['Lęki Napadowe', 'Wysoka Tolerancja Stresu'],
    ['Lęki Napadowe', 'Zimna Krew'],
    ['Naiwny', 'Wyczucie kłamstwa'],
    ['Naiwny', 'Uliczny Spryt'],
    ['Naiwny', 'Nieufny'],
    ['Naiwny', 'Paranoik'],
    ['Szczerość do bólu', 'Mistrz Blefu'],
    ['Brak Empatii', 'Empatyczny'],
    ['Brak Empatii', 'Spowiednik'],
    ['Brak Empatii', 'Zaufana twarz'],
    ['Mizantrop', 'Empatyczny'],
    ['Mizantrop', 'Zaufana twarz'],
    ['Wstydliwy', 'Charyzmatyczny'],
    ['Wstydliwy', 'Autorytet'],
    ['Oszpecony', 'Zjawiskowa Uroda'],
    ['Znana twarz', 'Mistrz przebrań'],
    ['Znana twarz', 'Kameleon'],
    ['Obcy akcent', 'Kameleon'],
    ['Przybysz', 'Podziemny Nowy Jork'],
    ['Przybysz', 'Taksówkarz'],
    ['Przybysz', 'Dachy Manhattanu'],
    ['Przybysz', 'Dzielnica rodzinna'],
    ['Przybysz', 'Plotki salonów'],
    ['Przybysz', 'Nabrzeże'],
    ['Wykluczony z dzielnicy', 'Dzielnica rodzinna'],
    ['Zła Reputacja', 'Zaufana twarz'],
    ['Pechowiec', 'Łut szczęścia'],
    ['Kryzys wiary', 'Niezłomna wola'],
    ['Lęk Wysokości', 'Dachy Manhattanu'],
    ['Lęk Wysokości', 'Parkour'],
    ['Klaustrofobia', 'Kontorsjonista'],
    ['Klaustrofobia', 'Podziemny Nowy Jork'],
    ['Lęk przed ciemnością', 'Podziemny Nowy Jork'],
    ['Lęk Tłumu', 'Czytanie tłumu'],
    ['Lęk Tłumu', 'Kameleon'],
    ['Zwierzęta jej nie lubią', 'Język zwierząt'],
    ['Zwierzęta jej nie lubią', 'Tresura'],
    ['Zwierzęta jej nie lubią', 'Jeździec urodzony'],
    ['Lęk przed psami', 'Język zwierząt'],
    ['Lęk przed psami', 'Tresura'],
    ['Depresja', 'Wrodzony Optymizm'],
    ['Furiat', 'Zimna Krew'],
    ['Furiat', 'Spokój ducha'],
    ['Trauma Pourazowa', 'Spokój ducha'],
];

function zw_pula(int $poziom, int $bonus = 0): int { return ZW_PULA_START + intdiv(max(0, $poziom), ZW_CO_POZIOMOW) + $bonus; }

/** Wszystkie wykluczenia jako pary: nowe pary + stare grupy z karta.php (każda z każdą). */
function zw_pary(array $grupy_stare = []): array {
    $p = ZW_PARY;
    foreach ($grupy_stare as $g) { $g = array_values($g); for ($i = 0; $i < count($g); $i++) for ($j = $i + 1; $j < count($g); $j++) $p[] = [$g[$i], $g[$j]]; }
    return $p;
}

/** Walidacja wyboru. Zwraca komunikat błędu albo null. */
function zw_waliduj(array $z, array $w, int $pula, array $pary): ?string {
    if (count($z) + count($w) > ZW_MAKS) return 'Łącznie można rozdysponować najwyżej ' . ZW_MAKS . ' PZ (Zalety + Wady).';
    if ($pula + count($w) - count($z) < 0) return 'Za mało PZ: Zalety kosztują po 1 PZ, Wady oddają po 1 PZ.';
    $all = array_flip(array_merge($z, $w));
    foreach ($pary as [$a, $b]) if (isset($all[$a], $all[$b])) return "Wykluczające się: $a oraz $b.";
    return null;
}
