<?php
/* the-abyss/config/zlecenia_pl.php — zleceniodawcy, kontrakty i skoki: POLSKA (Warszawa, Kraków).
   Format opisany w config/zleceniodawcy.php. */
return [
'npc' => [
  'zdzislaw' => ['n' => 'Pan Zdzisław z komisu', 'typ' => 'Auta',       'kl' => 'Szabrownik', 'o' => 'Komis na Grochowie. Auta z Niemiec, papiery z niczego, gwarancja do bramy.', 'dar' => 'tepe'],
  'brzeska'  => ['n' => 'Mecenas Brzeska',       'typ' => 'Prawo',      'kl' => null,         'o' => 'Kancelaria przy Nowym Świecie. Wyciąga ludzi z dołka szybciej, niż zdążą się przyznać.', 'usluga' => 'adwokat', 'dar' => 'palna'],
  'grazyna'  => ['n' => 'Grażyna „Kantor”',      'typ' => 'Gotówka',    'kl' => null,         'o' => 'Kantor na Dworcu Centralnym. Wymienia wszystko na wszystko i nic nie zapisuje.', 'wrog' => 'seba', 'dar' => 'ostrze'],
  'szyszko'  => ['n' => 'Bogdan Szyszko',        'typ' => 'Baza TIR',   'kl' => 'Szabrownik', 'o' => 'Kierownik bazy TIR-ów pod Łodzią. Ładunki u niego znikają i pojawiają się z powrotem w innych ilościach.', 'dar' => 'tepe'],
  'piotr'    => ['n' => 'Ksiądz Piotr',          'typ' => 'Parafia',    'kl' => 'Egzekutor',  'o' => 'Proboszcz z Kazimierza. Zna grzechy połowy dzielnicy i czasem prosi, żeby ktoś odpokutował je szybciej.', 'dar' => 'tepe'],
  'seba'     => ['n' => 'Seba z Pragi',          'typ' => 'Windykacja', 'kl' => 'Egzekutor',  'o' => 'Zna każde podwórko na Ząbkowskiej i każdego, kto komuś wisi pieniądze.', 'wrog' => 'grazyna', 'dar' => 'tepe'],
  'lis'      => ['n' => 'Dr Lis',                'typ' => 'Klinika',    'kl' => 'Inżynier',   'o' => 'Prywatna klinika na Mokotowie. Recepty, zaświadczenia i milczenie w jednej cenie.', 'dar' => 'ostrze'],
],
'kontrakty' => [
  'pl_vin'       => ['npc' => 'zdzislaw', 't' => 'Nowy numer VIN', 'kl' => 'Szabrownik', 'um' => 'Mechanika i Naprawa', 'tr' => 50, 'kasa' => 3400, 'xp' => 20, 'cz' => 0, 'gl' => false, 'rep' => 0, 'lvl' => 1,
                     'b' => 'Passat z Hamburga ma od jutra mieć inny numer nadwozia. Tak, żeby diagnosta na przeglądzie się nie zawahał.'],
  'pl_laweta'    => ['npc' => 'zdzislaw', 't' => 'Laweta z Poznania', 'kl' => null, 'um' => 'Prowadzenie Pojazdów', 'tr' => 45, 'kasa' => 5000, 'xp' => 26, 'cz' => 15, 'gl' => false, 'rep' => 0, 'lvl' => 5,
                     'b' => 'Trzy auta na lawecie, granica w Świecku o czwartej rano. Papiery są w schowku, nie czytaj ich.'],
  'pl_dziupla'   => ['npc' => 'zdzislaw', 't' => 'Dziupla na Białołęce', 'kl' => 'Szabrownik', 'um' => 'Demolka i Siłowe Wejścia', 'tr' => 35, 'kasa' => 9800, 'xp' => 38, 'cz' => 25, 'gl' => true, 'rep' => 2, 'lvl' => 22,
                     'b' => 'Konkurencja rozbiera auta w garażu przy Modlińskiej. Chcę części. Garaż niech się sam o siebie martwi.', 'mat' => ['czesci_mechaniczne' => 5]],
  'pl_akt'       => ['npc' => 'brzeska', 't' => 'Akt oskarżenia', 'kl' => null, 'um' => 'Prawo i Administracja', 'tr' => 50, 'kasa' => 4200, 'xp' => 22, 'cz' => 0, 'gl' => false, 'rep' => 0, 'lvl' => 1,
                     'b' => 'W akcie oskarżenia mojego klienta jest błąd formalny. Jeszcze go nie ma. Ma być do poniedziałku.'],
  'pl_swiadkowie'=> ['npc' => 'brzeska', 't' => 'Świadek z Pragi', 'kl' => null, 'um' => 'Psychologia i Empatia', 'tr' => 45, 'kasa' => 5200, 'xp' => 26, 'cz' => 10, 'gl' => false, 'rep' => 1, 'lvl' => 8,
                     'b' => 'Pan Waldemar pamięta tablicę rejestracyjną. Pomóż mu zapomnieć, bez przemocy i bez prezentów, które dałoby się wycenić.'],
  'pl_prokurator'=> ['npc' => 'brzeska', 't' => 'Teczka prokuratora', 'kl' => 'Szabrownik', 'um' => 'Włamywanie Elektroniczne', 'tr' => 35, 'kasa' => 10500, 'xp' => 40, 'cz' => 25, 'gl' => false, 'rep' => 2, 'lvl' => 25,
                     'b' => 'Prokurator Nowak zabiera akta do domu na Saską Kępę. W środę wieczorem jest na siłowni.'],
  'pl_dolary'    => ['npc' => 'grazyna', 't' => 'Dolary w walizce', 'kl' => null, 'um' => 'Topografia i Nawigacja', 'tr' => 50, 'kasa' => 3800, 'xp' => 22, 'cz' => 0, 'gl' => false, 'rep' => 0, 'lvl' => 1,
                     'b' => 'Walizka z Centralnego do Wilanowa. Taksówką nie, metrem nie. Wymyśl coś.'],
  'pl_banknoty'  => ['npc' => 'grazyna', 't' => 'Banknoty z drukarni', 'kl' => 'Inżynier', 'um' => 'Fałszerstwo Dokumentów', 'tr' => 40, 'kasa' => 6800, 'xp' => 30, 'cz' => 15, 'gl' => false, 'rep' => 1, 'lvl' => 12,
                     'b' => 'Ktoś wpuścił do obiegu fałszywe setki i wszyscy patrzą na mój kantor. Znajdź drukarnię, zanim znajdzie ją policja.'],
  'pl_kurs'      => ['npc' => 'grazyna', 't' => 'Kurs dnia', 'kl' => null, 'um' => 'Matematyka i Rachunkowość', 'tr' => 35, 'kasa' => 11800, 'xp' => 42, 'cz' => 20, 'gl' => false, 'rep' => 2, 'lvl' => 28,
                     'b' => 'Trzy kantory, trzy waluty i jeden dzień, kiedy kursy rozjadą się o dwa procent. Przepuść przez nie milion, zanim ktoś zauważy.'],
  'pl_paleta'    => ['npc' => 'szyszko', 't' => 'Brakująca paleta', 'kl' => 'Szabrownik', 'um' => 'Handel i Wycena', 'tr' => 50, 'kasa' => 3600, 'xp' => 20, 'cz' => 0, 'gl' => false, 'rep' => 0, 'lvl' => 1,
                     'b' => 'Z ciężarówki do Kutna ma zniknąć jedna paleta elektroniki. Kierowca ma podpisać, że wszystko się zgadza.', 'mat' => ['elektronika' => 2]],
  'pl_tachograf' => ['npc' => 'szyszko', 't' => 'Tachograf', 'kl' => 'Inżynier', 'um' => 'Elektronika', 'tr' => 45, 'kasa' => 5400, 'xp' => 26, 'cz' => 12, 'gl' => false, 'rep' => 1, 'lvl' => 8,
                     'b' => 'Kierowca jechał dwadzieścia godzin bez przerwy. Tachograf ma pokazać, że spał w Strykowie.'],
  'pl_cysterna'  => ['npc' => 'szyszko', 't' => 'Cysterna bez papierów', 'kl' => 'Szabrownik', 'um' => 'Prowadzenie Pojazdów', 'sprz' => ['pancerz' => 5], 'tr' => 35, 'kasa' => 10200, 'xp' => 38, 'cz' => 25, 'gl' => true, 'rep' => 2, 'lvl' => 22,
                     'b' => 'Cysterna paliwa z Białorusi stoi na parkingu pod Terespolem. Ma dojechać do bazy, zanim przyjdą po nią właściciele.', 'mat' => ['syntetyki' => 4]],
  'pl_ofiara'    => ['npc' => 'piotr', 't' => 'Skarbonka na remont', 'kl' => 'Egzekutor', 'um' => 'Znajomość Półświatka', 'tr' => 50, 'kasa' => 2600, 'xp' => 26, 'cz' => 0, 'gl' => false, 'rep' => 0, 'lvl' => 1,
                     'b' => 'Ktoś ukradł skarbonkę na remont dzwonnicy. Wiem, że chłopak spod Hali Targowej. Niech odda i niech przyjdzie do spowiedzi.'],
  'pl_dzwon'     => ['npc' => 'piotr', 't' => 'Dzwon z Mogiły', 'kl' => 'Egzekutor', 'um' => 'Historia i Antykwariat', 'tr' => 45, 'kasa' => 5000, 'xp' => 30, 'cz' => 15, 'gl' => false, 'rep' => 1, 'lvl' => 8,
                     'b' => 'Zabytkowy dzwon z kościoła w Mogile wystawiono na aukcji w Wiedniu. Aukcja ma się nie odbyć, a dzwon wrócić.'],
  'pl_pielgrzymka'=>['npc' => 'piotr', 't' => 'Spokojna pielgrzymka', 'kl' => 'Egzekutor', 'um' => 'Zastraszanie', 'sprz' => ['pancerz' => 8], 'tr' => 40, 'kasa' => 6400, 'xp' => 34, 'cz' => 20, 'gl' => true, 'rep' => 2, 'lvl' => 20,
                     'b' => 'Kibole z Nowej Huty zapowiedzieli, że pielgrzymka nie przejdzie przez ich osiedle. Przejdzie, i to w ciszy.'],
  'pl_dlug'      => ['npc' => 'seba', 't' => 'Dług na Ząbkowskiej', 'kl' => 'Egzekutor', 'um' => 'Perswazja i Negocjacje', 'tr' => 55, 'kasa' => 3000, 'xp' => 22, 'cz' => 0, 'gl' => true, 'rep' => 0, 'lvl' => 1,
                     'b' => 'Mariusz od trzech miesięcy mówi, że odda w piątek. Dziś jest piątek.'],
  'pl_bar'       => ['npc' => 'seba', 't' => 'Bar mleczny', 'kl' => 'Egzekutor', 'um' => 'Boks Uliczny', 'sprz' => ['cios' => 'tepe'], 'tr' => 45, 'kasa' => 5600, 'xp' => 28, 'cz' => 10, 'gl' => true, 'rep' => 1, 'lvl' => 8,
                     'b' => 'Nowy właściciel baru na Brzeskiej nie płaci za ochronę, bo mówi, że nie potrzebuje. Pokaż mu, że potrzebuje.'],
  'pl_uciekinier'=> ['npc' => 'seba', 't' => 'Uciekinier do Hamburga', 'kl' => 'Egzekutor', 'um' => 'Tropienie', 'tr' => 35, 'kasa' => 9600, 'xp' => 38, 'cz' => 22, 'gl' => true, 'rep' => 2, 'lvl' => 20,
                     'b' => 'Krystian wziął kasę całej ekipy i jedzie autokarem do Hamburga. Autokar staje w Świecku o północy.'],
  'pl_recepty'   => ['npc' => 'lis', 't' => 'Recepty z bloczka', 'kl' => null, 'um' => 'Medycyna Akademicka', 'tr' => 50, 'kasa' => 3800, 'xp' => 22, 'cz' => 0, 'gl' => false, 'rep' => 0, 'lvl' => 1,
                     'b' => 'Pięćdziesiąt recept wypisanych tak, żeby apteka nie zadzwoniła do żadnego lekarza.'],
  'pl_pacjent'   => ['npc' => 'lis', 't' => 'Pacjent bez nazwiska', 'kl' => null, 'um' => 'Medycyna Uliczna', 'tr' => 45, 'kasa' => 5800, 'xp' => 28, 'cz' => 12, 'gl' => false, 'rep' => 1, 'lvl' => 10,
                     'b' => 'W garażu na Służewcu leży człowiek z kulą w ramieniu. Do szpitala nie pojedzie. Pomóż mu, zanim przestanie oddychać.'],
  'pl_laboratorium'=>['npc' => 'lis', 't' => 'Laboratorium w Pruszkowie', 'kl' => 'Inżynier', 'um' => 'Chemia i Farmakologia', 'tr' => 30, 'kasa' => 14200, 'xp' => 46, 'cz' => 30, 'gl' => false, 'rep' => 2, 'lvl' => 34,
                     'b' => 'Hurtownia farmaceutyczna w Pruszkowie ma w nocy przeterminować cały zapas jednego leku. Na papierze. Lek przyjedzie do mnie.'],
],
'skoki' => [
  'pl_konwoj' => ['npc' => 'szyszko', 'wsp' => 'zdzislaw', 't' => 'Konwój na A2', 'rep' => 2, 'lvl' => 16, 'lup' => 30000, 'xp' => 120, 'mat' => ['czesci_mechaniczne' => 10, 'elektronika' => 6],
    'b' => 'Ciężarówka z elektroniką jedzie z Łodzi do Berlina. Bogdan zna trasę, Zdzisław ma wóz, który ją dogoni. Ładunek ma zmienić właściciela na parkingu pod Koninem.',
    'etapy' => [
      ['n' => 'Trasa', 'min' => 8, 'o' => 'Konwój rusza o 22:00. Dwa wozy ochrony, jedna naczepa.', 'op' => [
        ['t' => 'Kup trasę od dyspozytora', 'o' => 'Dyspozytor ma kredyt na mieszkanie i małe dziecko.', 'um' => 'Perswazja i Negocjacje', 'tr' => 60, 'koszt' => 1500, 'premia' => 10],
        ['t' => 'Nadajnik pod naczepą', 'o' => 'Mały, magnetyczny i od Bogdana.', 'kl' => 'Inżynier', 'um' => 'Elektronika', 'tr' => 45, 'premia' => 10],
        ['t' => 'Jedź za nimi A2', 'o' => 'Nocą na autostradzie wszyscy wyglądają tak samo.', 'um' => 'Prowadzenie Pojazdów', 'tr' => 50, 'premia' => 5]]],
      ['n' => 'Parking', 'min' => 14, 'o' => 'MOP pod Koninem. Kierowca idzie na kawę, ochrona zostaje w aucie.', 'op' => [
        ['t' => 'Otwórz naczepę', 'o' => 'Plomba, kłódka i zamek, który pamięta lata dziewięćdziesiąte.', 'kl' => 'Szabrownik', 'um' => 'Otwieranie Zamków (Wytrychy)', 'tr' => 45],
        ['t' => 'Zagłusz łączność ochrony', 'o' => 'Radio szumi, telefony tracą zasięg.', 'kl' => 'Inżynier', 'um' => 'Elektronika', 'tr' => 40, 'gl' => true],
        ['t' => 'Porozmawiaj z ochroną', 'o' => 'Dwóch chłopaków z agencji za trzy tysiące miesięcznie. Nie będą bohaterami.', 'kl' => 'Egzekutor', 'um' => 'Zastraszanie', 'sprz' => ['pancerz' => 5], 'tr' => 45, 'gl' => true]]],
      ['n' => 'Przeładunek', 'min' => 12, 'o' => 'Naczepa pełna kartonów. Zdzisław podjeżdża busem.', 'op' => [
        ['t' => 'Tylko najdroższe kartony', 'o' => 'Laptopy i telefony, reszta zostaje.', 'um' => 'Handel i Wycena', 'tr' => 50, 'lup' => 100],
        ['t' => 'Cała naczepa', 'o' => 'Odczepić, podpiąć i odjechać.', 'kl' => 'Szabrownik', 'um' => 'Mechanika i Naprawa', 'tr' => 35, 'lup' => 160, 'gl' => true],
        ['t' => 'Kartony i sejf kierowcy', 'o' => 'Kierowca wozi w kabinie gotówkę na paliwo. Dużo paliwa.', 'um' => 'Kieszonkostwo', 'tr' => 30, 'lup' => 180]]],
      ['n' => 'Ucieczka', 'min' => 10, 'ucieczka' => true, 'o' => 'Na bramkach w Koninie stoi radiowóz. Może przypadkiem.', 'op' => [
        ['t' => 'Boczne drogi przez Kujawy', 'o' => 'Wolniej, ale bez kamer.', 'um' => 'Topografia i Nawigacja', 'tr' => 50],
        ['t' => 'Autostradą na pełnym gazie', 'o' => 'Bus Zdzisława jedzie szybciej, niż wygląda.', 'um' => 'Prowadzenie Pojazdów', 'tr' => 45],
        ['t' => 'Zostaw część w lesie', 'o' => 'Kartony pod plandeką, wrócisz po nie za tydzień. Może.', 'um' => 'Przetrwanie w Dziczy', 'tr' => 60, 'lup' => -30]]],
    ]],
  'pl_sukiennice' => ['npc' => 'piotr', 'wsp' => 'brzeska', 't' => 'Noc w Sukiennicach', 'rep' => 2, 'lvl' => 30, 'lup' => 52000, 'xp' => 150, 'mat' => ['syntetyki' => 8, 'elektronika' => 8],
    'b' => 'Obraz skradziony parafii przed wojną wisi w Sukiennicach jako depozyt prywatnego kolekcjonera. Ksiądz Piotr chce go z powrotem. Mecenas Brzeska dopilnuje, żeby nikt nie mógł udowodnić, skąd wrócił.',
    'etapy' => [
      ['n' => 'Plan budynku', 'min' => 10, 'o' => 'Galeria na piętrze, alarm z 2019 roku i nocny stróż, który lubi krzyżówki.', 'op' => [
        ['t' => 'Plany z urzędu konserwatora', 'o' => 'Mecenas zna kogoś w urzędzie.', 'um' => 'Prawo i Administracja', 'tr' => 55, 'premia' => 10],
        ['t' => 'Wycieczka z przewodnikiem', 'o' => 'Trzy razy w tygodniu, zawsze z innym przewodnikiem.', 'um' => 'Szpiegostwo i Inwigilacja', 'tr' => 50, 'premia' => 10],
        ['t' => 'Kup schemat alarmu', 'o' => 'Instalator ma długi w kasynie przy Wiślnej.', 'kl' => 'Inżynier', 'um' => 'Perswazja i Negocjacje', 'tr' => 60, 'koszt' => 3000, 'premia' => 10]]],
      ['n' => 'Wejście', 'min' => 15, 'o' => 'Rynek o trzeciej w nocy. Ostatni turyści, dorożki i patrol straży miejskiej.', 'op' => [
        ['t' => 'Dachem od Sukiennic', 'o' => 'Stare dachówki i świetlik nad galerią.', 'kl' => 'Szabrownik', 'um' => 'Wspinaczka Wysokogórska', 'tr' => 40],
        ['t' => 'Wyłącz alarm galerii', 'o' => 'Centralka w piwnicy i piętnaście sekund na kod.', 'kl' => 'Inżynier', 'um' => 'Włamywanie Elektroniczne', 'tr' => 40],
        ['t' => 'Stróż i jego krzyżówka', 'o' => 'Stróż nie chce kłopotów. Pomóż mu ich uniknąć.', 'kl' => 'Egzekutor', 'um' => 'Zastraszanie', 'tr' => 45, 'gl' => true]]],
      ['n' => 'Obraz', 'min' => 15, 'o' => 'Obraz w ciężkiej ramie, czujnik ruchu pod podłogą i kopia, którą przyniosłeś w tubie.', 'op' => [
        ['t' => 'Podmień na kopię', 'o' => 'Nikt się nie zorientuje przez miesiąc.', 'um' => 'Sztuki Plastyczne i Rzemiosło', 'tr' => 40, 'lup' => 130],
        ['t' => 'Wytnij z ramy', 'o' => 'Szybko i bez kopii. Rano będzie wiadomo.', 'kl' => 'Szabrownik', 'um' => 'Otwieranie Zamków (Wytrychy)', 'tr' => 50, 'lup' => 100, 'gl' => true],
        ['t' => 'Obraz i dwie ryciny z gabloty', 'o' => 'Kolekcjoner nie zgłosi rycin, bo sam je ukradł.', 'um' => 'Historia i Antykwariat', 'tr' => 30, 'lup' => 180]]],
      ['n' => 'Ucieczka', 'min' => 10, 'ucieczka' => true, 'o' => 'Hejnał z Mariackiej. Za godzinę Rynek się budzi.', 'op' => [
        ['t' => 'Dorożką przez Planty', 'o' => 'Nikt nie zatrzymuje dorożek.', 'um' => 'Jazda Konna', 'tr' => 50],
        ['t' => 'Piwnicami pod Rynkiem', 'o' => 'Stare korytarze prowadzą aż pod Grodzką.', 'um' => 'Topografia i Nawigacja', 'tr' => 50],
        ['t' => 'Zostaw ryciny na plebanii', 'o' => 'Ksiądz Piotr je przechowa. Albo nie odda.', 'um' => 'Skradanie', 'tr' => 60, 'lup' => -30]]],
    ]],
],
];
