<?php
/* the-abyss/config/zlecenia_ny.php — zleceniodawcy, kontrakty i skoki: NEW YORK.
   Format opisany w config/zleceniodawcy.php. Dopisujesz nowy kontrakt = nowa linia w 'kontrakty'. */
return [
'npc' => [
  'olowek' => ['n' => 'Wiktor „Ołówek” Sadowski', 'typ' => 'Włamania',   'kl' => 'Szabrownik', 'o' => 'Księgowy rodzin z Brighton Beach. Liczy wszystko dwa razy i płaci co do centa.', 'dar' => 'ostrze'],
  'lucia'  => ['n' => 'Mama Lucía Ferreira',      'typ' => 'Kurierka',   'kl' => null,         'o' => 'Pralnia w Queens, która pierze nie tylko koszule. Zawsze najpierw nakarmi.', 'dar' => 'palna'],
  'dex'    => ['n' => 'Dex Harlan',               'typ' => 'Wywiad',     'kl' => 'Inżynier',   'o' => 'Fixer z dachu parkingu w Hell\'s Kitchen. Sprzedaje informacje i kupuje je drożej, niż są warte.', 'wrog' => 'vale', 'dar' => 'palna'],
  'wrona'  => ['n' => 'Ojciec Tomasz Wrona',      'typ' => 'Przysługi',  'kl' => 'Egzekutor',  'o' => 'Proboszcz z Greenpointu. Prosi o przysługi dla parafian i nigdy nie pyta, jak zostały wykonane.', 'wrog' => 'irena', 'dar' => 'tepe'],
  'rosa'   => ['n' => 'Rosa Kwan',                'typ' => 'Port',       'kl' => 'Szabrownik', 'o' => 'Kierowniczka zmiany w porcie Red Hook. Wie, który kontener nie ma właściciela.', 'dar' => 'tepe'],
  'silas'  => ['n' => 'Silas Oduya',              'typ' => 'Prawo',      'kl' => null,         'o' => 'Adwokat bez szyldu. Pracuje po 22:00 i przyjmuje w barze.', 'usluga' => 'adwokat', 'dar' => 'palna'],
  'irena'  => ['n' => '„Babcia” Irena Mazur',     'typ' => 'Windykacja', 'kl' => 'Egzekutor',  'o' => 'Lichwiarka z Ridgewood. Częstuje sernikiem, zanim przypomni o odsetkach.', 'wrog' => 'wrona', 'dar' => 'tepe'],
  'vale'   => ['n' => 'Konrad Vale',              'typ' => 'Korporacja', 'kl' => 'Inżynier',   'o' => 'Dyrektor ochrony Vale Dynamics. Legalny, dopóki nikt nie patrzy.', 'wrog' => 'dex', 'dar' => 'palna'],
],
'kontrakty' => [
  'ny_ksiega'     => ['npc' => 'olowek', 't' => 'Księga, która nie istnieje', 'kl' => 'Szabrownik', 'um' => 'Otwieranie Zamków (Wytrychy)', 'tr' => 50, 'kasa' => 4200, 'xp' => 25, 'cz' => 12, 'gl' => false, 'rep' => 0, 'lvl' => 1,
                      'b' => 'Biuro rachunkowe na 47. ulicy trzyma drugą kopię ksiąg. Oryginał ma zniknąć, kopia trafić do mnie. Nikt nie może zauważyć, że ktoś tam był.'],
  'ny_faktury'    => ['npc' => 'olowek', 't' => 'Faktury z sufitu', 'kl' => null, 'um' => 'Fałszerstwo Dokumentów', 'tr' => 45, 'kasa' => 3500, 'xp' => 20, 'cz' => 0, 'gl' => false, 'rep' => 0, 'lvl' => 1,
                      'b' => 'Hurtownia w Bensonhurst potrzebuje trzydziestu faktur na towar, którego nigdy nie było. Papier dam, pieczątki są twoje.'],
  'ny_sejf'       => ['npc' => 'olowek', 't' => 'Sejf pod biurkiem', 'kl' => 'Szabrownik', 'um' => 'Włamywanie Elektroniczne', 'tr' => 40, 'kasa' => 7800, 'xp' => 32, 'cz' => 20, 'gl' => true, 'rep' => 1, 'lvl' => 12,
                      'b' => 'Pan Abramow trzyma w biurze sejf z zamkiem cyfrowym i przekonaniem, że nikt o nim nie wie. Chcę zawartość. Sejf może zostać.'],
  'ny_pranie'     => ['npc' => 'lucia', 't' => 'Pranie na sucho', 'kl' => null, 'um' => 'Prowadzenie Pojazdów', 'tr' => 45, 'kasa' => 5200, 'xp' => 25, 'cz' => 15, 'gl' => false, 'rep' => 0, 'lvl' => 1,
                      'b' => 'Torba z Queens do Jersey City. Trzy punkty kontrolne po drodze. Zjedz coś, zanim wyjedziesz, i jedź tak, jakby nic w niej nie było.'],
  'ny_torby'      => ['npc' => 'lucia', 't' => 'Trzy torby, jeden taksówkarz', 'kl' => null, 'um' => 'Topografia i Nawigacja', 'tr' => 50, 'kasa' => 3800, 'xp' => 20, 'cz' => 0, 'gl' => false, 'rep' => 0, 'lvl' => 1,
                      'b' => 'Hector wie, dokąd jechać, ale nie wie, co wiezie. Jedź z nim i dopilnuj, żeby nie zaczął się zastanawiać.'],
  'ny_jersey'     => ['npc' => 'lucia', 't' => 'Most na Jersey', 'kl' => null, 'um' => 'Prowadzenie Pojazdów', 'sprz' => ['pancerz' => 5], 'tr' => 35, 'kasa' => 9800, 'xp' => 36, 'cz' => 25, 'gl' => true, 'rep' => 1, 'lvl' => 15,
                      'b' => 'Tym razem ktoś wie, że jedziesz. Samochód jest opancerzony, ty też powinieneś być.'],
  'ny_kamery'     => ['npc' => 'dex', 't' => 'Ślepa kamera', 'kl' => 'Inżynier', 'um' => 'Elektronika', 'tr' => 50, 'kasa' => 3900, 'xp' => 22, 'cz' => 10, 'gl' => false, 'rep' => 0, 'lvl' => 1,
                      'b' => 'Kamera nad lombardem na Dziewiątej Alei ma od jutra oglądać ścianę. Nikt nie może pomyśleć, że to celowe.'],
  'ny_pluskwa'    => ['npc' => 'dex', 't' => 'Pluskwa w Hell\'s Kitchen', 'kl' => 'Inżynier', 'um' => 'Szpiegostwo i Inwigilacja', 'tr' => 45, 'kasa' => 5600, 'xp' => 28, 'cz' => 18, 'gl' => false, 'rep' => 1, 'lvl' => 8,
                      'b' => 'Irlandczycy spotykają się w pubie przy 44. W loży przy oknie ma być mikrofon, zanim przyjdą w czwartek.'],
  'ny_serwer'     => ['npc' => 'dex', 't' => 'Serwerownia na 34. piętrze', 'kl' => 'Inżynier', 'um' => 'Hakowanie Terminali', 'tr' => 35, 'kasa' => 11500, 'xp' => 42, 'cz' => 25, 'gl' => false, 'rep' => 2, 'lvl' => 25,
                      'b' => 'Vale Dynamics trzyma kopie maili zarządu. Chcę wszystko z ostatniego kwartału. Konrad nie może się dowiedzieć, że to ja.'],
  'ny_kielich'    => ['npc' => 'wrona', 't' => 'Kielich z Greenpointu', 'kl' => 'Egzekutor', 'um' => 'Znajomość Półświatka', 'tr' => 55, 'kasa' => 2400, 'xp' => 30, 'cz' => 10, 'gl' => true, 'rep' => 1, 'lvl' => 1,
                      'b' => 'Ktoś ukradł kielich z zakrystii. Wiem, że leży w lombardzie na Manhattan Avenue. Wiem też, że lombard ma dwóch ochroniarzy.'],
  'ny_zofia'      => ['npc' => 'wrona', 't' => 'Anioł stróż pani Zofii', 'kl' => 'Egzekutor', 'um' => 'Zastraszanie', 'tr' => 50, 'kasa' => 3000, 'xp' => 22, 'cz' => 0, 'gl' => false, 'rep' => 0, 'lvl' => 1,
                      'b' => 'Właściciel kamienicy wyłącza pani Zofii ogrzewanie, żeby się wyprowadziła. Porozmawiaj z nim. Ogrzewanie ma wrócić do niedzieli.'],
  'ny_procesja'   => ['npc' => 'wrona', 't' => 'Procesja bez incydentów', 'kl' => 'Egzekutor', 'um' => 'Taktyka Wojskowa', 'sprz' => ['pancerz' => 8], 'tr' => 40, 'kasa' => 6400, 'xp' => 34, 'cz' => 20, 'gl' => true, 'rep' => 2, 'lvl' => 20,
                      'b' => 'Gang z Bushwick zapowiedział, że w tym roku procesja nie przejdzie przez ich ulicę. Przejdzie.'],
  'ny_kontener'   => ['npc' => 'rosa', 't' => 'Kontener 44-B', 'kl' => 'Szabrownik', 'um' => 'Mechanika i Naprawa', 'tr' => 40, 'kasa' => 6800, 'xp' => 30, 'cz' => 18, 'gl' => false, 'rep' => 0, 'lvl' => 5,
                      'b' => 'Kontener stoi od miesiąca, papiery zgubione. Otwórz, wynieś, co da się unieść, i zamknij tak, żeby plomba wyglądała na nietkniętą.', 'mat' => ['czesci_mechaniczne' => 3]],
  'ny_plomby'     => ['npc' => 'rosa', 't' => 'Nowe plomby', 'kl' => 'Szabrownik', 'um' => 'Sztuki Plastyczne i Rzemiosło', 'tr' => 50, 'kasa' => 3600, 'xp' => 20, 'cz' => 0, 'gl' => false, 'rep' => 0, 'lvl' => 1,
                      'b' => 'Celnicy zmienili wzór plomb. Potrzebuję dwudziestu nowych, takich, żeby celnik nie zauważył różnicy nawet pod lupą.'],
  'ny_dzwig'      => ['npc' => 'rosa', 't' => 'Dźwig numer trzy', 'kl' => 'Szabrownik', 'um' => 'Demolka i Siłowe Wejścia', 'tr' => 35, 'kasa' => 10200, 'xp' => 38, 'cz' => 25, 'gl' => true, 'rep' => 2, 'lvl' => 22,
                      'b' => 'Dźwig nr 3 ma dziś w nocy awarię. Kiedy ochrona pobiegnie go oglądać, kontener z nabrzeża C ma zjechać na ciężarówkę.', 'mat' => ['zlom_stalowy' => 8]],
  'ny_swiadek'    => ['npc' => 'silas', 't' => 'Świadek, który się zawahał', 'kl' => null, 'um' => 'Psychologia i Empatia', 'tr' => 50, 'kasa' => 4600, 'xp' => 24, 'cz' => 0, 'gl' => false, 'rep' => 0, 'lvl' => 1,
                      'b' => 'Pani Delgado widziała za dużo i mówi o tym za głośno. Przekonaj ją, że się pomyliła. Bez gróźb. Groźby zostawiają ślad w aktach.'],
  'ny_akta'       => ['npc' => 'silas', 't' => 'Akta z archiwum sądu', 'kl' => null, 'um' => 'Prawo i Administracja', 'tr' => 45, 'kasa' => 5400, 'xp' => 28, 'cz' => 15, 'gl' => false, 'rep' => 1, 'lvl' => 6,
                      'b' => 'Teczka 17/B w archiwum sądu okręgowego ma mieć o jedną stronę mniej. Archiwista wychodzi na papierosa o 15:10.'],
  'ny_alibi'      => ['npc' => 'silas', 't' => 'Alibi na wtorek', 'kl' => null, 'um' => 'Aktorstwo i Charakteryzacja', 'tr' => 40, 'kasa' => 7200, 'xp' => 32, 'cz' => 12, 'gl' => false, 'rep' => 2, 'lvl' => 18,
                      'b' => 'Mój klient był we wtorek w kasynie w Atlantic City. Kamery mają to pokazać. Ty będziesz nim przez cztery godziny.'],
  'ny_czynsz'     => ['npc' => 'irena', 't' => 'Spóźniony czynsz', 'kl' => 'Egzekutor', 'um' => 'Perswazja i Negocjacje', 'tr' => 55, 'kasa' => 3100, 'xp' => 22, 'cz' => 0, 'gl' => true, 'rep' => 0, 'lvl' => 1,
                      'b' => 'Pan Kowalczyk z baru na Myrtle zalega trzy miesiące. Nie łam mu rąk. On nimi nalewa.'],
  'ny_dentysta'   => ['npc' => 'irena', 't' => 'Dentysta z Ridgewood', 'kl' => 'Egzekutor', 'um' => 'Zastraszanie', 'sprz' => ['cios' => 'tepe'], 'tr' => 45, 'kasa' => 5900, 'xp' => 28, 'cz' => 10, 'gl' => true, 'rep' => 1, 'lvl' => 8,
                      'b' => 'Pożyczył na nowy gabinet i mówi, że nie ma z czego oddać. Ma. Gabinet jest bardzo ładny.'],
  'ny_bukmacher'  => ['npc' => 'irena', 't' => 'Bukmacher, który zniknął', 'kl' => 'Egzekutor', 'um' => 'Tropienie', 'tr' => 35, 'kasa' => 9400, 'xp' => 38, 'cz' => 22, 'gl' => true, 'rep' => 2, 'lvl' => 20,
                      'b' => 'Lenny przyjął zakłady na finał i wyjechał razem z kasą. Ktoś go widział w motelu przy Turnpike. Przywieź pieniądze. Lenny może zostać.'],
  'ny_prototyp'   => ['npc' => 'vale', 't' => 'Prototyp w bagażniku', 'kl' => 'Inżynier', 'um' => 'Robotyka i Mechatronika', 'tr' => 40, 'kasa' => 8800, 'xp' => 34, 'cz' => 20, 'gl' => false, 'rep' => 0, 'lvl' => 15,
                      'b' => 'Nasz inżynier wyniósł prototyp drona w bagażniku. Odzyskaj go, zanim sprzeda go Chińczykom. Inżyniera zwolniliśmy.', 'mat' => ['elektronika' => 3]],
  'ny_karty'      => ['npc' => 'vale', 't' => 'Karty dostępu', 'kl' => 'Szabrownik', 'um' => 'Kieszonkostwo', 'tr' => 50, 'kasa' => 4800, 'xp' => 24, 'cz' => 0, 'gl' => false, 'rep' => 0, 'lvl' => 10,
                      'b' => 'Trzech menedżerów Harper Pharma je lunch w tym samym barze. Ich karty dostępu mają być u mnie przed deserem i z powrotem przed rachunkiem.'],
  'ny_konkurencja'=> ['npc' => 'vale', 't' => 'Dzień otwarty u konkurencji', 'kl' => 'Inżynier', 'um' => 'Włamywanie Elektroniczne', 'tr' => 30, 'kasa' => 15500, 'xp' => 46, 'cz' => 30, 'gl' => false, 'rep' => 2, 'lvl' => 35,
                      'b' => 'Harper Pharma otwiera laboratorium dla prasy. Laboratorium piętro niżej nie jest otwarte dla nikogo. Chcę zdjęcia każdej tablicy.'],
],
'skoki' => [
  'ny_terminal4' => ['npc' => 'rosa', 'wsp' => 'dex', 't' => 'Terminal 4, Red Hook', 'rep' => 2, 'lvl' => 15, 'lup' => 30000, 'xp' => 120, 'mat' => ['czesci_mechaniczne' => 12, 'zlom_stalowy' => 20],
    'b' => 'W kontenerze bez właściciela stoi towar, o którym nikt nie może głośno mówić. Rosa zna rozkład zmian, Dex zna kamery. Reszta należy do ciebie.',
    'etapy' => [
      ['n' => 'Rozpoznanie', 'min' => 8, 'o' => 'Port za dnia wygląda niewinnie. Masz godzinę, żeby dowiedzieć się, gdzie w nocy stoją ludzie.', 'op' => [
        ['t' => 'Przekup dokera', 'o' => 'Stary Mike powie wszystko za odpowiednią kwotę.', 'um' => 'Perswazja i Negocjacje', 'tr' => 60, 'koszt' => 1500, 'premia' => 10],
        ['t' => 'Przejrzyj nagrania z portu', 'o' => 'Dex dał ci dostęp do archiwum kamer z ostatniego tygodnia.', 'kl' => 'Inżynier', 'um' => 'Hakowanie Terminali', 'tr' => 45, 'premia' => 10],
        ['t' => 'Obserwuj z dachu magazynu', 'o' => 'Lornetka, termos i sześć godzin cierpliwości.', 'um' => 'Szpiegostwo i Inwigilacja', 'tr' => 50, 'premia' => 5]]],
      ['n' => 'Wejście', 'min' => 14, 'o' => 'Terminal 4 stoi w mgle. Z budki przy bramie A dochodzi radio. Brama B jest ciemna. O 02:20 przyjeżdża zmiana.', 'op' => [
        ['t' => 'Wytrych do bramy B', 'o' => 'Cicho i szybko. Brama B nie ma kamery od wtorku.', 'kl' => 'Szabrownik', 'um' => 'Otwieranie Zamków (Wytrychy)', 'tr' => 45],
        ['t' => 'Wyłącz zasilanie terminalu', 'o' => 'Ciemność na sześć minut. Wszyscy zauważą, nikt nie zobaczy.', 'kl' => 'Inżynier', 'um' => 'Elektronika', 'tr' => 40, 'gl' => true],
        ['t' => 'Przejdź przez ochronę', 'o' => 'Dwóch ochroniarzy w budce. Wejdziesz, ale będzie głośno.', 'kl' => 'Egzekutor', 'um' => 'Zastraszanie', 'sprz' => ['pancerz' => 5], 'tr' => 45, 'gl' => true]]],
      ['n' => 'Robota', 'min' => 12, 'o' => 'Kontener stoi tam, gdzie mówiła Rosa. W biurze kierownika zmiany pali się lampka nad sejfem.', 'op' => [
        ['t' => 'Tylko kontener', 'o' => 'Bierzesz, po co przyszedłeś, i nic więcej.', 'kl' => 'Szabrownik', 'um' => 'Mechanika i Naprawa', 'tr' => 50, 'lup' => 100],
        ['t' => 'Sejf kierownika', 'o' => 'Zamek cyfrowy, stary model. W środku coś, co kierownik wolałby zachować dla siebie.', 'um' => 'Włamywanie Elektroniczne', 'tr' => 35, 'lup' => 140],
        ['t' => 'Kontener i sejf', 'o' => 'Chciwość to też plan. Tylko trudniejszy.', 'um' => 'Kondycja i Wytrzymałość', 'tr' => 25, 'lup' => 190, 'gl' => true]]],
      ['n' => 'Ucieczka', 'min' => 10, 'ucieczka' => true, 'o' => 'Z Hamilton Avenue słychać syreny. Ktoś zadzwonił.', 'op' => [
        ['t' => 'Łódź Rosy', 'o' => 'Motorówka przy nabrzeżu C, bez świateł, prosto na Staten Island.', 'um' => 'Rybołówstwo i Żegluga', 'tr' => 50],
        ['t' => 'Furgonetka przez Gowanus', 'o' => 'Wąskie ulice, mosty zwodzone i kierowca, który zna każdy z nich.', 'um' => 'Prowadzenie Pojazdów', 'tr' => 45],
        ['t' => 'Rozdzielić się', 'o' => 'Każdy w swoją stronę, łup w trzech torbach. Jedna może nie dotrzeć.', 'um' => 'Topografia i Nawigacja', 'tr' => 60, 'lup' => -30]]],
    ]],
  'ny_gala' => ['npc' => 'vale', 'wsp' => 'silas', 't' => 'Gala w Vale Tower', 'rep' => 2, 'lvl' => 30, 'lup' => 55000, 'xp' => 150, 'mat' => ['elektronika' => 10, 'syntetyki' => 8],
    'b' => 'Konrad Vale chce wiedzieć, co jego zarząd ukrywa przed nim samym. Dane leżą na 60. piętrze, a na 58. trwa gala dobroczynna.',
    'etapy' => [
      ['n' => 'Zaproszenie', 'min' => 10, 'o' => 'Lista gości jest zamknięta od tygodnia. Na liście musisz być ty.', 'op' => [
        ['t' => 'Podrób zaproszenie', 'o' => 'Karton z tłoczeniem, hologram i numer seryjny z zeszłego roku.', 'um' => 'Fałszerstwo Dokumentów', 'tr' => 50, 'premia' => 10],
        ['t' => 'Kup miejsce od kelnera', 'o' => 'Kelnerzy też mają długi.', 'um' => 'Perswazja i Negocjacje', 'tr' => 65, 'koszt' => 3000, 'premia' => 5],
        ['t' => 'Wejdź jako ochrona', 'o' => 'Czarny garnitur, słuchawka w uchu i mina, której nikt nie zaczepi.', 'kl' => 'Egzekutor', 'um' => 'Aktorstwo i Charakteryzacja', 'tr' => 45, 'premia' => 10]]],
      ['n' => 'Sala balowa', 'min' => 15, 'o' => 'Kwartet smyczkowy, szampan i dyrektor finansowy, który pije trzeci kieliszek.', 'op' => [
        ['t' => 'Rozmowa z dyrektorem finansowym', 'o' => 'Po czwartym kieliszku powie ci hasło do windy.', 'um' => 'Sztuka Uwodzenia', 'tr' => 45, 'lup' => 30],
        ['t' => 'Sklonuj kartę ochroniarza', 'o' => 'Jedno potrącenie przy barze, dwie sekundy przy czytniku w kieszeni.', 'kl' => 'Szabrownik', 'um' => 'Kieszonkostwo', 'tr' => 45, 'premia' => 10],
        ['t' => 'Pluskwa w sali konferencyjnej', 'o' => 'Zarząd spotyka się po gali. Będziesz słyszeć każde słowo.', 'kl' => 'Inżynier', 'um' => 'Elektronika', 'tr' => 45, 'lup' => 20]]],
      ['n' => 'Serwerownia', 'min' => 15, 'o' => '60. piętro. Chłód, szum wentylatorów i drzwi, które otwierają się tylko od środka.', 'op' => [
        ['t' => 'Włam się do serwera', 'o' => 'Trzy warstwy szyfrowania i administrator, który nie zmienia haseł.', 'kl' => 'Inżynier', 'um' => 'Hakowanie Terminali', 'tr' => 35, 'lup' => 120],
        ['t' => 'Szyb windowy', 'o' => 'Dwa piętra po linie w ciemności. Drzwi serwerowni od strony szybu nie mają czujnika.', 'kl' => 'Szabrownik', 'um' => 'Wspinaczka Wysokogórska', 'tr' => 40, 'lup' => 110],
        ['t' => 'Wymuś kod od strażnika', 'o' => 'Strażnik na 60. zna kod i bardzo chce wrócić do domu.', 'kl' => 'Egzekutor', 'um' => 'Zastraszanie', 'sprz' => ['cios' => 'palna'], 'tr' => 40, 'lup' => 100, 'gl' => true]]],
      ['n' => 'Wyjście', 'min' => 10, 'ucieczka' => true, 'o' => 'Alarm na 60. piętrze jest cichy. Ochrona na dole już wie.', 'op' => [
        ['t' => 'Wyjdź razem z gośćmi', 'o' => 'Płaszcz z szatni, taksówka w kolejce i uśmiech do portiera.', 'um' => 'Etykieta i Dobre Manery', 'tr' => 55],
        ['t' => 'Winda towarowa', 'o' => 'Kuchnia, rampa i zaułek za budynkiem.', 'um' => 'Skradanie', 'tr' => 50],
        ['t' => 'Dach i helikopter Deksa', 'o' => 'Dex obiecał, że będzie. Dex zwykle dotrzymuje obietnic.', 'um' => 'Pilotaż', 'tr' => 35, 'lup' => 30]]],
    ]],
],
];
