<?php
/* the-abyss/config/zlecenia_la.php — zleceniodawcy, kontrakty i skoki: LOS ANGELES.
   Format opisany w config/zleceniodawcy.php. */
return [
'npc' => [
  'neon'    => ['n' => 'Dolores „Neon” Vega', 'typ' => 'Wozy',        'kl' => null,         'o' => 'Wypożyczalnia aut w Van Nuys. Ma wóz na każdą ucieczkę i nie pyta, dokąd jedziesz.', 'dar' => 'palna'],
  'aldridge'=> ['n' => 'Trent Aldridge',      'typ' => 'Skandale',    'kl' => null,         'o' => 'Producent filmowy. Płaci za ciszę więcej niż za scenariusze.', 'wrog' => 'hollis', 'dar' => 'ostrze'],
  'paik'    => ['n' => 'Mister Paik',         'typ' => 'Elektronika', 'kl' => 'Inżynier',   'o' => 'Hurtownik z Koreatown. Wszystko, co ma baterię, przechodzi przez jego magazyn.', 'dar' => 'palna'],
  'hollis'  => ['n' => 'Sierżant Hollis (em.)','typ' => 'Patrole',    'kl' => null,         'o' => 'Były policjant LAPD. Sprzedaje rozkłady patroli i wie, który raport można zgubić.', 'usluga' => 'adwokat', 'wrog' => 'aldridge', 'dar' => 'palna'],
  'lupe'    => ['n' => 'Lupe Ortega',         'typ' => 'Ulica',       'kl' => 'Egzekutor',  'o' => 'Szefowa food trucków na East LA. Czterdzieści okienek, czterdzieści par oczu.', 'dar' => 'ostrze'],
  'cole'    => ['n' => '„Surfer” Cole Brandt','typ' => 'Przystań',    'kl' => 'Szabrownik', 'o' => 'Przemyt przez przystań w Marina del Rey. Opalony, spokojny i zawsze o krok przed strażą.', 'dar' => 'tepe'],
  'oksana'  => ['n' => 'Madame Oksana',       'typ' => 'Przyjęcia',   'kl' => null,         'o' => 'Organizuje prywatne przyjęcia w Hollywood Hills. Goście wychodzą z sekretami mniej, niż przyszli.', 'dar' => 'ostrze'],
],
'kontrakty' => [
  'la_tablice'   => ['npc' => 'neon', 't' => 'Czyste tablice', 'kl' => 'Szabrownik', 'um' => 'Mechanika i Naprawa', 'tr' => 50, 'kasa' => 3600, 'xp' => 20, 'cz' => 0, 'gl' => false, 'rep' => 0, 'lvl' => 1,
                     'b' => 'Pięć wozów wraca z roboty w Compton. Mają wyjechać z mojego garażu z innymi numerami i innym kolorem.'],
  'la_pogon'     => ['npc' => 'neon', 't' => 'Pościg na zamówienie', 'kl' => null, 'um' => 'Prowadzenie Pojazdów', 'tr' => 45, 'kasa' => 5400, 'xp' => 26, 'cz' => 12, 'gl' => true, 'rep' => 0, 'lvl' => 5,
                     'b' => 'Klient chce, żeby policja goniła czerwone Camaro przez pół godziny, dokładnie wtedy, kiedy jego ludzie są w Downtown. Prowadzisz Camaro.'],
  'la_konwoj'    => ['npc' => 'neon', 't' => 'Konwój przez pustynię', 'kl' => null, 'um' => 'Topografia i Nawigacja', 'sprz' => ['pancerz' => 5], 'tr' => 35, 'kasa' => 10400, 'xp' => 38, 'cz' => 25, 'gl' => true, 'rep' => 2, 'lvl' => 22,
                     'b' => 'Trzy ciężarówki do Barstow. Na drodze 15 czekają ludzie, którzy też chcą ten ładunek.'],
  'la_zdjecia'   => ['npc' => 'aldridge', 't' => 'Zdjęcia z Malibu', 'kl' => null, 'um' => 'Włamywanie Elektroniczne', 'tr' => 45, 'kasa' => 5200, 'xp' => 26, 'cz' => 15, 'gl' => false, 'rep' => 0, 'lvl' => 5,
                     'b' => 'Paparazzo z Santa Monica ma zdjęcia mojej gwiazdy z niewłaściwą osobą. Karty pamięci mają zniknąć razem z kopiami w chmurze.'],
  'la_recenzja'  => ['npc' => 'aldridge', 't' => 'Recenzja przed premierą', 'kl' => null, 'um' => 'Perswazja i Negocjacje', 'tr' => 50, 'kasa' => 3400, 'xp' => 20, 'cz' => 0, 'gl' => false, 'rep' => 0, 'lvl' => 1,
                     'b' => 'Krytyk z „Variety” widział film i go nienawidzi. Do piątku ma go polubić. Jak, to twoja sprawa.'],
  'la_scenariusz'=> ['npc' => 'aldridge', 't' => 'Scenariusz z sejfu', 'kl' => 'Szabrownik', 'um' => 'Otwieranie Zamków (Wytrychy)', 'tr' => 35, 'kasa' => 9600, 'xp' => 36, 'cz' => 20, 'gl' => false, 'rep' => 2, 'lvl' => 20,
                     'b' => 'Konkurencyjne studio trzyma w sejfie scenariusz, który jest kopią mojego. Chcę wiedzieć, kto im go sprzedał.'],
  'la_telefony'  => ['npc' => 'paik', 't' => 'Skrzynia bez faktury', 'kl' => 'Inżynier', 'um' => 'Elektronika', 'tr' => 50, 'kasa' => 3800, 'xp' => 22, 'cz' => 10, 'gl' => false, 'rep' => 0, 'lvl' => 1,
                     'b' => 'Dwieście telefonów z zablokowanymi numerami seryjnymi. Do jutra mają być czyste i gotowe do sprzedaży.', 'mat' => ['elektronika' => 2]],
  'la_bramki'    => ['npc' => 'paik', 't' => 'Bramki w porcie Long Beach', 'kl' => 'Inżynier', 'um' => 'Hakowanie Terminali', 'tr' => 40, 'kasa' => 7400, 'xp' => 32, 'cz' => 18, 'gl' => false, 'rep' => 1, 'lvl' => 12,
                     'b' => 'System celny w Long Beach ma przez dwie godziny widzieć mój kontener jako pusty.'],
  'la_drony'     => ['npc' => 'paik', 't' => 'Rój nad Koreatown', 'kl' => 'Inżynier', 'um' => 'Robotyka i Mechatronika', 'tr' => 35, 'kasa' => 12200, 'xp' => 42, 'cz' => 25, 'gl' => false, 'rep' => 2, 'lvl' => 28,
                     'b' => 'Ktoś śledzi moje ciężarówki dronami. Przejmij jeden, a ja dowiem się, kto płaci za resztę.', 'mat' => ['elektronika' => 5]],
  'la_raport'    => ['npc' => 'hollis', 't' => 'Zgubiony raport', 'kl' => null, 'um' => 'Prawo i Administracja', 'tr' => 50, 'kasa' => 4000, 'xp' => 22, 'cz' => 0, 'gl' => false, 'rep' => 0, 'lvl' => 1,
                     'b' => 'Raport z zatrzymania na Sunset ma trafić do złej szuflady. Wiem, która to szuflada. Ty masz tam dojść.'],
  'la_patrol'    => ['npc' => 'hollis', 't' => 'Rozkład patroli', 'kl' => null, 'um' => 'Szpiegostwo i Inwigilacja', 'tr' => 45, 'kasa' => 5000, 'xp' => 26, 'cz' => 15, 'gl' => false, 'rep' => 0, 'lvl' => 8,
                     'b' => 'Nowy komendant zmienił rozkład w Rampart. Chcę go mieć, zanim ktoś inny go kupi.'],
  'la_dowody'    => ['npc' => 'hollis', 't' => 'Magazyn dowodów', 'kl' => 'Szabrownik', 'um' => 'Skradanie', 'tr' => 35, 'kasa' => 11000, 'xp' => 40, 'cz' => 25, 'gl' => false, 'rep' => 2, 'lvl' => 26,
                     'b' => 'W magazynie dowodów na 77. Street leży torba, która nigdy nie powinna była tam trafić.'],
  'la_okienko'   => ['npc' => 'lupe', 't' => 'Okienko przy Whittier', 'kl' => 'Egzekutor', 'um' => 'Zastraszanie', 'tr' => 50, 'kasa' => 3200, 'xp' => 22, 'cz' => 0, 'gl' => true, 'rep' => 0, 'lvl' => 1,
                     'b' => 'Ktoś ustawił truck na moim rogu. Rozumiem konkurencję. Nie rozumiem braku szacunku.'],
  'la_haracz'    => ['npc' => 'lupe', 't' => 'Haracz od haraczu', 'kl' => 'Egzekutor', 'um' => 'Boks Uliczny', 'sprz' => ['cios' => 'tepe'], 'tr' => 45, 'kasa' => 6000, 'xp' => 30, 'cz' => 10, 'gl' => true, 'rep' => 1, 'lvl' => 10,
                     'b' => 'Chłopaki z Boyle Heights biorą opłaty od moich kucharzy. Od dziś biorą je ode mnie. Przekaż im to.'],
  'la_wesele'    => ['npc' => 'lupe', 't' => 'Wesele bez strzałów', 'kl' => 'Egzekutor', 'um' => 'Mediacja i Rozwiązywanie Konfliktów', 'tr' => 35, 'kasa' => 9000, 'xp' => 38, 'cz' => 20, 'gl' => false, 'rep' => 2, 'lvl' => 22,
                     'b' => 'Moja siostrzenica wychodzi za chłopaka z drugiej strony rzeki. Obie rodziny przyjdą uzbrojone. Wesele ma się odbyć do końca.'],
  'la_boja'      => ['npc' => 'cole', 't' => 'Boja numer siedem', 'kl' => 'Szabrownik', 'um' => 'Pływanie i Nurkowanie', 'tr' => 45, 'kasa' => 4600, 'xp' => 24, 'cz' => 12, 'gl' => false, 'rep' => 0, 'lvl' => 4,
                     'b' => 'Pod boją numer siedem wisi wodoszczelna skrzynka. Straż przybrzeżna pływa tamtędy co czterdzieści minut.'],
  'la_jacht'     => ['npc' => 'cole', 't' => 'Jacht na sprzedaż', 'kl' => 'Szabrownik', 'um' => 'Rybołówstwo i Żegluga', 'tr' => 40, 'kasa' => 8200, 'xp' => 34, 'cz' => 20, 'gl' => false, 'rep' => 1, 'lvl' => 15,
                     'b' => 'Właściciel „Blue Horizon” wyjechał na miesiąc. Jacht ma przez ten miesiąc pływać do Ensenady i z powrotem.'],
  'la_trumny'    => ['npc' => 'cole', 't' => 'Deski i trumny', 'kl' => 'Szabrownik', 'um' => 'Demolka i Siłowe Wejścia', 'tr' => 35, 'kasa' => 10800, 'xp' => 40, 'cz' => 25, 'gl' => true, 'rep' => 2, 'lvl' => 24,
                     'b' => 'Magazyn tartaczny w San Pedro trzyma w skrzyniach z deskami coś cięższego niż drewno. Przynieś mi skrzynie, deski zostaw.', 'mat' => ['zlom_stalowy' => 6]],
  'la_goscie'    => ['npc' => 'oksana', 't' => 'Lista gości', 'kl' => null, 'um' => 'Etykieta i Dobre Manery', 'tr' => 50, 'kasa' => 3800, 'xp' => 22, 'cz' => 0, 'gl' => false, 'rep' => 0, 'lvl' => 1,
                     'b' => 'Na sobotnie przyjęcie przychodzi senator. Ktoś musi go zająć rozmową, kiedy fotograf zrobi zdjęcie jego towarzyszce.'],
  'la_tajemnica' => ['npc' => 'oksana', 't' => 'Sekret z garderoby', 'kl' => null, 'um' => 'Sztuka Uwodzenia', 'tr' => 45, 'kasa' => 6200, 'xp' => 28, 'cz' => 12, 'gl' => false, 'rep' => 1, 'lvl' => 10,
                     'b' => 'Aktorka z serialu medycznego trzyma w garderobie notes z nazwiskami. Chcę ten notes na jedną noc.'],
  'la_wille'     => ['npc' => 'oksana', 't' => 'Willa na wzgórzu', 'kl' => 'Szabrownik', 'um' => 'Włamywanie Elektroniczne', 'tr' => 30, 'kasa' => 14800, 'xp' => 46, 'cz' => 30, 'gl' => false, 'rep' => 2, 'lvl' => 34,
                     'b' => 'Gospodarz przyjęcia trzyma kolekcję zegarków w pokoju, do którego nie wpuszcza nawet żony. Goście zajmą go do trzeciej.'],
],
'skoki' => [
  'la_premiera' => ['npc' => 'aldridge', 'wsp' => 'neon', 't' => 'Noc premiery', 'rep' => 2, 'lvl' => 18, 'lup' => 34000, 'xp' => 125, 'mat' => ['elektronika' => 6, 'syntetyki' => 6],
    'b' => 'Kopia filmu za dwieście milionów wyjeżdża z laboratorium w Burbank do kina na Hollywood Boulevard. Trent chce, żeby dotarła o godzinę później i z jedną kopią mniej.',
    'etapy' => [
      ['n' => 'Trasa', 'min' => 8, 'o' => 'Konwój studia jedzie trzema samochodami. Tylko jeden wiezie dysk.', 'op' => [
        ['t' => 'Kup trasę od kierowcy', 'o' => 'Kierowca furgonetki ma długi w kasynie.', 'um' => 'Perswazja i Negocjacje', 'tr' => 60, 'koszt' => 1500, 'premia' => 10],
        ['t' => 'Namierz GPS konwoju', 'o' => 'Nadajniki studia są stare i nieszyfrowane.', 'kl' => 'Inżynier', 'um' => 'Elektronika', 'tr' => 45, 'premia' => 10],
        ['t' => 'Jedź za nimi', 'o' => 'Jedno auto z tyłu, dwie przecznice odstępu.', 'um' => 'Prowadzenie Pojazdów', 'tr' => 50, 'premia' => 5]]],
      ['n' => 'Zatrzymanie', 'min' => 12, 'o' => 'Skrzyżowanie Cahuenga i Franklin. Światła zmieniają się co czterdzieści sekund.', 'op' => [
        ['t' => 'Zablokuj światła', 'o' => 'Czerwone przez dziesięć minut na całej ulicy.', 'kl' => 'Inżynier', 'um' => 'Hakowanie Terminali', 'tr' => 45],
        ['t' => 'Wypadek na zamówienie', 'o' => 'Dolores dała ci wóz, którego nie żal.', 'kl' => 'Szabrownik', 'um' => 'Prowadzenie Pojazdów', 'tr' => 45, 'gl' => true],
        ['t' => 'Zatrzymaj ich na ulicy', 'o' => 'Kamizelka, odznaka z lombardu i pewny krok.', 'kl' => 'Egzekutor', 'um' => 'Aktorstwo i Charakteryzacja', 'sprz' => ['pancerz' => 5], 'tr' => 45]]],
      ['n' => 'Kopia', 'min' => 12, 'o' => 'Dysk leży w walizce przykutej do nadgarstka ochroniarza.', 'op' => [
        ['t' => 'Skopiuj dysk na miejscu', 'o' => 'Dziewięćdziesiąt sekund transferu i walizka wraca na miejsce.', 'kl' => 'Inżynier', 'um' => 'Programowanie', 'tr' => 40, 'lup' => 110],
        ['t' => 'Otwórz kajdanki', 'o' => 'Ochroniarz nawet nie poczuje.', 'kl' => 'Szabrownik', 'um' => 'Otwieranie Zamków (Wytrychy)', 'tr' => 40, 'lup' => 130],
        ['t' => 'Zabierz całą walizkę', 'o' => 'Ochroniarz poczuje.', 'kl' => 'Egzekutor', 'um' => 'Krav Maga', 'tr' => 35, 'lup' => 170, 'gl' => true]]],
      ['n' => 'Ucieczka', 'min' => 10, 'ucieczka' => true, 'o' => 'Helikopter telewizji już krąży nad Hollywood. Nad tobą.', 'op' => [
        ['t' => 'Autostrada 101', 'o' => 'Sto sześćdziesiąt na godzinę w stronę Valley.', 'um' => 'Prowadzenie Pojazdów', 'tr' => 45],
        ['t' => 'Kanał burzowy', 'o' => 'Suchy, ciemny i nieoznaczony na mapach dla turystów.', 'um' => 'Topografia i Nawigacja', 'tr' => 50],
        ['t' => 'Wmieszaj się w tłum premiery', 'o' => 'Czerwony dywan, tysiąc ludzi, żadnych pytań.', 'um' => 'Moda i Wizerunek', 'tr' => 55, 'lup' => -20]]],
    ]],
  'la_marina' => ['npc' => 'cole', 'wsp' => 'paik', 't' => 'Mgła nad Marina del Rey', 'rep' => 2, 'lvl' => 32, 'lup' => 58000, 'xp' => 150, 'mat' => ['zlom_stalowy' => 18, 'elektronika' => 8],
    'b' => 'Kartel z Tijuany przypływa jachtem z ładunkiem dla Paika. Cole wie, że jacht przypłynie. Nie wie, czy Paik zapłaci. Paik woli, żeby ładunek zniknął po drodze.',
    'etapy' => [
      ['n' => 'Przystań', 'min' => 10, 'o' => 'Mgła od oceanu, dwadzieścia pomostów i jeden, który ma kamerę.', 'op' => [
        ['t' => 'Przekup ochronę mariny', 'o' => 'Stróż ma ośmioro wnucząt.', 'um' => 'Perswazja i Negocjacje', 'tr' => 60, 'koszt' => 3000, 'premia' => 10],
        ['t' => 'Wyłącz kamerę pomostu', 'o' => 'Jeden kabel, jedna skrzynka, trzy minuty.', 'kl' => 'Inżynier', 'um' => 'Elektronika', 'tr' => 45, 'premia' => 10],
        ['t' => 'Podpłyń od wody', 'o' => 'Ponton, kombinezon i zimna woda Pacyfiku.', 'um' => 'Pływanie i Nurkowanie', 'tr' => 45, 'premia' => 10]]],
      ['n' => 'Pokład', 'min' => 15, 'o' => 'Na jachcie czterech ludzi. Dwóch śpi, dwóch pali na rufie.', 'op' => [
        ['t' => 'Wejdź od dziobu', 'o' => 'Cicho, po cumie, w cieniu kabiny.', 'kl' => 'Szabrownik', 'um' => 'Skradanie', 'tr' => 45],
        ['t' => 'Zakłóć radio jachtu', 'o' => 'Nikt nie wezwie pomocy, kiedy zaczniesz.', 'kl' => 'Inżynier', 'um' => 'Elektronika', 'tr' => 45],
        ['t' => 'Zajmij się rufą', 'o' => 'Dwóch palaczy, jeden cios na każdego.', 'kl' => 'Egzekutor', 'um' => 'Krav Maga', 'sprz' => ['cios' => 'tepe'], 'tr' => 45, 'gl' => true]]],
      ['n' => 'Ładownia', 'min' => 15, 'o' => 'Skrzynie w ładowni i sejf kapitana w kabinie.', 'op' => [
        ['t' => 'Tylko skrzynie', 'o' => 'Tyle, ile uniesie ponton.', 'um' => 'Kondycja i Wytrzymałość', 'tr' => 50, 'lup' => 100],
        ['t' => 'Sejf kapitana', 'o' => 'Kapitan trzyma tam zapłatę za cały kurs.', 'kl' => 'Szabrownik', 'um' => 'Włamywanie Elektroniczne', 'tr' => 35, 'lup' => 140],
        ['t' => 'Cały jacht', 'o' => 'Po co nosić skrzynie, skoro można odpłynąć z nimi?', 'um' => 'Rybołówstwo i Żegluga', 'tr' => 25, 'lup' => 200, 'gl' => true]]],
      ['n' => 'Odpłynięcie', 'min' => 10, 'ucieczka' => true, 'o' => 'Na brzegu zapalają się światła. Kartel ma w porcie więcej niż jedną łódź.', 'op' => [
        ['t' => 'Na pełnym gazie na południe', 'o' => 'Szybciej niż straż, wolniej niż kule.', 'um' => 'Rybołówstwo i Żegluga', 'tr' => 45],
        ['t' => 'Zgaś światła i czekaj w mgle', 'o' => 'Mgła jest gęsta. Oby do rana.', 'um' => 'Przetrwanie w Dziczy', 'tr' => 50],
        ['t' => 'Zatop część ładunku', 'o' => 'Lżejsza łódź, mniejszy łup.', 'um' => 'Topografia i Nawigacja', 'tr' => 60, 'lup' => -30]]],
    ]],
],
];
